^.<sent>$[][
<!DOCTYPE html PUBLIC "-\/\/W3C\/\/DTD HTML 3.2\/\/EN">
<html>
<head>
<meta name="generator" content=
"media wiki xml converter. copyright James Michael DuPont 2009">
<title><\/title>
<\/head>
<body>
    <h1><\/h1>
<p>]^*Kosova$ ^*Airlines$[
<strong>]^Kosovo<np><loc><sg>$[<\/strong> ]^(<lpar>$^know<vblex><pp>$ ^in<pr>$[ <a href='Albanian language|Albanian'>]^Albanian<adj>$ ^language<n><sg>$|^Albanian<n><sg>$[<\/a> ]^as<pr>$[ <strong>]^*Kosova$[<\/strong>]^,<cm>$[  ]^and<cnjcoo>$ ^in<pr>$ ^English<adj>$ ^language<n><sg>$|^English<adj>$^\]<rpar>$ ^simply<adv>$ ^as<pr>$ ^Kosovo<np><loc><sg>$^)<rpar>$^.<sent>$[  ]^The<det><def><sp>$ ^province<n><sg>$^'s<gen>$ ^final<adj>$ ^status<n><sg>$ ^have<vbhaver><pri><p3><sg>$ ^yet<adv>$ ^to<pr>$ ^be<vbser><inf>$ ^determine<vblex><pp>$^;<sent>$ ^talk<n><pl>$ ^on<pr>$ ^this<det><dem><sg>$ ^issue<n><sg>$ ^be<vbser><pres>$ ^schedule<vblex><pp>$ ^for<pr>$ ^later<adv>$ ^in<pr>$[ <a href='2005'>]^2005<num>$[<\/a>]^.<sent>$^.<sent>$[][<\/p>
<a name="Geography"><\/a><h2>]^Geography<n><sg>$^.<sent>$[][<\/h2><p>]^With<pr>$ ^a<det><ind><sg>$ ^area<n><sg>$ ^of<pr>$[ <a href='1 E10 m2|10,887'>]^1<num>$ ^*E$^10<num>$ ^*m$^2<num>$|^10,887<num>$[<\/a> <a href='square kilometre|km&amp;sup2;'>]^square<adj>$ ^kilometre<n><sg>$|^*km$[&amp;]^*sup$^2<num>$^;<sent>$[<\/a> ]^and<cnjcoo>$ ^a<det><ind><sg>$ ^population<n><sg>$ ^of<pr>$ ^almost<adv>$ ^2<num>$ ^million<num><sp>$ ^on<pr>$ ^the<det><def><sp>$ ^*eve$ ^of<pr>$ ^the<det><def><sp>$ ^1999<num>$ ^crisis<n><sg>$^,<cm>$ ^Kosovo<np><loc><sg>$ ^border<n><pl>$ ^with<pr>$[ <a href='Montenegro'>]^Montenegro<np><loc><sg>$[<\/a> ]^to<pr>$ ^the<det><def><sp>$ ^northwest<n><sg>$^,<cm>$ ^the<det><def><sp>$ ^rest<n><sg>$ ^of<pr>$[ <a href='Serbia'>]^*Serbia$[<\/a> ]^(<lpar>$^often<adv>$ ^call<vblex><pp>$ "[<a href='Serbia proper'>]^*Serbia$ ^proper<adj>$[<\/a>]" ^in<pr>$ ^English<adj>$^)<rpar>$ ^to<pr>$ ^the<det><def><sp>$ ^north<adj><sint>$ ^and<cnjcoo>$ ^east<n><sg>$^,<cm>$ ^the<det><def><sp>$[ <a href='Republic of Macedonia'>]^Republic<n><sg>$ ^of<pr>$ ^Macedonia<np><ant><f><sg>$[<\/a> ]^to<pr>$ ^the<det><def><sp>$ ^south<adj><sint>$^,<cm>$ ^and<cnjcoo>$[ <a href='Albania'>]^*Albania$[<\/a> ]^to<pr>$ ^the<det><def><sp>$ ^southwest<n><sg>$^.<sent>$ ^The<det><def><sp>$ ^large<adj><sint><sup>$ ^city<n><pl>$ ^be<vbser><pres>$[ <a href='Prishtina|Pri&amp;#353;tina'>]^*Prishtina$|^*Pri$[&amp;]#^353<num>$^;<sent>$^*tina$[<\/a>]^,<cm>$ ^the<det><def><sp>$ ^capital<n><sg>$^,<cm>$ ^with<pr>$ ^estimate<vblex><pp>$ ^500,000<num>$ ^inhabitant<n><pl>$^,<cm>$ ^and<cnjcoo>$[ <a href='Prizren'>]^*Prizren$[<\/a> ]^in<pr>$ ^the<det><def><sp>$ ^southwest<n><sg>$ ^with<pr>$ ^120,000<num>$^:<sent>$ ^five<num><sp>$ ^other<det><ind><sp>$ ^town<n><pl>$ ^have<vblex><inf>$ ^population<n><pl>$ ^in<pr>$ ^excess<n><sg>$ ^of<pr>$ ^50,000<num>$^.<sent>$^.<sent>$[][<\/p>
<a name="Name"><\/a><h2>]^Name<n><sg>$^.<sent>$[][<\/h2><p>]^The<det><def><sp>$ ^province<n><sg>$ ^be<vbser><pri><p3><sg>$ ^best<adv>$ ^know<vblex><pp>$ ^as<pr>$[ <strong>]^Kosovo<np><loc><sg>$[<\/strong> ]^-<guio>$ ^this<det><dem><sg>$ ^name<n><sg>$ ^have<vbhaver><pri><p3><sg>$ ^be<vbser><pp>$ ^the most<det><qnt><sp>$ ^widely<adv>$ ^use<vblex><pp>$ ^by<pr>$ ^map<n><pl>$ ^abroad<adv>$^.<sent>$ ^The<det><def><sp>$ ^alternative<adj>$ ^spelling<n><sg>$[ <em>]^*Kossovo$[<\/em> ]^be<vbser><past><p3><sg>$ ^frequently<adv>$ ^use<vblex><pp>$ ^until<pr>$ ^the<det><def><sp>$[ <a href='20th century'>]^early<adj><sint>$ ^20<num>$^*th$ ^century<n><sg>$[<\/a> ]^and<cnjcoo>$ ^before<cnjadv>$ ^that<prn><tn><mf><sg>$^,<cm>$[ <em>]^*Cassovo$[<\/em> ]^or<cnjcoo>$[ <em>]^*Cassua$[<\/em>]^,<cm>$ ^a<det><ind><sg>$[ <a href='Italian language|Italianisation'>]^Italian<adj>$ ^language<n><sg>$|^*Italianisation$[<\/a> ]^of<pr>$ ^the<det><def><sp>$ ^name<n><sg>$^.<sent>$^.<sent>$[][<\/p>
<p>]^The<det><def><sp>$ ^name<n><sg>$ ^Kosovo<np><loc><sg>$[ <a href='Image:Kosov.png|center|thumb|431px|All places in the world whose names begin with "Kosov"'>]^Image<n><sg>$^:<sent>$^*Kosov$^.<sent>$^*png$|^centre<n><sg>$|^thumb<n><sg>$|^431<num>$^*px$|^All<predet><sp>$ ^place<n><pl>$ ^in<pr>$ ^the<det><def><sp>$ ^world<adj>$ ^*whose$ ^name<n><pl>$ ^begin<vblex><inf>$ ^with<pr>$ "^*Kosov$"^.<sent>$[][<\/a><\/p>
<p><strong>]^*Kosova$[<\/strong> ]^(<lpar>$^pronounce<vblex><pp>$ "^*ko$^-<guio>$^SO<n><acr><sg>$^-<guio>$^*vah$"^)<rpar>$ ^be<vbser><pri><p3><sg>$ ^the<det><def><sp>$[ <a href='Albanian language|Albanian'>]^Albanian<adj>$ ^language<n><sg>$|^Albanian<adj>$[<\/a> ]^spelling<n><sg>$ ^for<pr>$ ^the<det><def><sp>$ ^province<n><sg>$^.<sent>$ ^Albanian<n><pl>$ ^tend<vblex><inf>$ ^to<pr>$ ^use<vblex><inf>$ "^*Kosova$" ^exclusively<adv>$ ^in<pr>$ ^preference<n><sg>$ ^to<pr>$ ^the<det><def><sp>$ ^*Serbian$ ^name<n><sg>$^,<cm>$ ^which<prn><itg><m><sp>$ ^many<det><qnt><pl>$ ^of<pr>$ ^prpers<prn><obj><p3><mf><pl>$ ^reject<vblex><pres>$ ^as a<pr>$ ^symbol<n><sg>$ ^of<pr>$ ^*Serbian$ ^*dominance$^.<sent>$ ^Prpers<prn><subj><p3><nt><sg>$ ^be<vbser><pri><p3><sg>$ ^also<adv>$ ^occasionally<adv>$ ^spell<vblex><pp>$ ^as<pr>$[ <em>]^*Kosov$Ã«[<\/em>]^;<sent>$ ^this<prn><tn><mf><sg>$ ^be<vbser><pri><p3><sg>$ ^due to the fact that<cnjadv>$ ^in<pr>$ ^Albanian<n><sg>$^,<cm>$ ^add<vblex><ger>$ ^the<det><def><sp>$ ^definite<adj>$ ^article<n><sg>$ ^to<pr>$ ^a<det><ind><sg>$ ^noun<n><sg>$ ^change<vblex><pri><p3><sg>$ ^the<det><def><sp>$ ^ending<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^word<n><sg>$^.<sent>$^.<sent>$[][<\/p>
<p> 
]^The<det><def><sp>$ ^Albanian<adj>$^-<guio>$^populate<vblex><pp>$ ^area<n><pl>$ ^of<pr>$ ^the<det><def><sp>$ ^province<n><sg>$ ^and<cnjcoo>$ ^*Albania$ ^itself<prn><ref><p3><nt><sg>$ ^tend<vblex><pres>$ ^to<pr>$ ^use<vblex><inf>$ "^*Kosova$" ^exclusively<adv>$^.<sent>$ "^Kosovo<np><loc><sg>$" ^be<vbser><pri><p3><sg>$ ^use<vblex><pp>$^,<cm>$ ^again<adv>$ ^almost<adv>$ ^exclusively<adv>$^,<cm>$ ^in<pr>$ ^the<det><def><sp>$ ^*Serb$^-<guio>$^populate<vblex><pp>$ ^north<adv>$ ^of<pr>$ ^the<det><def><sp>$ ^province<n><sg>$ ^and<cnjcoo>$ ^in<pr>$ ^the<det><def><sp>$ ^rest<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^former<adj>$[ <a href='Socialist Federal Republic of Yugoslavia|Yugoslavia'>]^Socialist<adj>$ ^Federal<adj>$ ^Republic<n><sg>$ ^of<pr>$ ^Yugoslavia<np><loc><sg>$|^Yugoslavia<np><loc><sg>$[<\/a>]^.<sent>$ ^The<det><def><sp>$ ^international<adj>$ ^community<n><sg>$ ^try<vblex><pri><p3><sg>$ ^to<pr>$ ^*steer$ ^a<det><ind><sg>$ ^*middle$ ^path<n><sg>$ ^by<pr>$ ^*referring$ ^formally<adv>$ ^to<pr>$ "^Kosovo<np><loc><sg>$\/^*Kosova$^.<sent>$" ^In<pr>$ ^practice<n><sg>$^,<cm>$ ^however<adv>$^,<cm>$ ^the<det><def><sp>$ ^*Serbian$ ^*variant$ ^be<vbser><pri><p3><sg>$ ^still<adv>$ ^the most<det><qnt><sp>$ ^frequently<adv>$ ^use<vblex><pp>$ ^outside<pr>$ ^of<pr>$ ^Kosovo<np><loc><sg>$ ^while<cnjadv>$ ^the<det><def><sp>$ ^Albanian<adj>$ ^*variant$ ^be<vbser><pri><p3><sg>$ ^widely<adv>$ ^use<vblex><pp>$ ^by<pr>$ "^*internationals$" ^within<pr>$ ^the<det><def><sp>$ ^province<n><sg>$^.<sent>$^.<sent>$[][<\/p>
<p>]^The<det><def><sp>$ ^use<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^two<num><sp>$ ^alternative<adj>$ ^name<n><pl>$ ^be<vbser><pri><p3><sg>$ ^a<det><ind><sg>$ ^highly<adv>$ ^sensitive<adj>$ ^political<adj>$ ^issue<n><sg>$ ^for<pr>$ ^both<det><ind><pl>$ ^*Serbs$ ^and<cnjcoo>$ ^Kosovo<np><loc><sg>$ ^Albanian<n><pl>$^,<cm>$ ^who<prn><itg><m><sp>$ ^regard<n><sg>$ ^the<det><def><sp>$ ^use<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^other<det><ind><sp>$ ^side<n><sg>$^'s<gen>$ ^name<n><sg>$ ^as<pr>$ ^be<vbser><ger>$ ^a<det><ind><sg>$ ^denial<n><sg>$ ^of<pr>$ ^their<det><pos><sp>$ ^own<adj>$ ^side<n><sg>$^'s<gen>$ ^territorial<adj>$ ^right<n><pl>$ ^(<lpar>$^in<pr>$ ^much<det><qnt><sg>$ ^the same<det><ind><sp>$ ^way<n><sg>$ ^that<cnjsub>$[ <a href='Macedonian Slavs|Macedonians'>]^*Macedonian$ ^*Slavs$|^*Macedonians$[<\/a> ]^and<cnjcoo>$[ <a href='Greece|Greeks'>]^Greece<np><loc><sg>$|^Greek<n><pl>$[<\/a> ]^have<vbhaver><inf>$ ^*disputed$ ^the<det><def><sp>$ ^name<n><sg>$ ^of<pr>$ ^the<det><def><sp>$[ <a href='Republic of Macedonia'>]^Republic<n><sg>$ ^of<pr>$ ^Macedonia<np><ant><f><sg>$[<\/a>]^)<rpar>$^.<sent>$ ^During<pr>$[ <a href='Kosovo War'>]^the<det><def><sp>$ ^Kosovo<np><loc><sg>$ ^War<n><sg>$[<\/a>]^,<cm>$[ <a href='United States'>]^United States<np><loc><sg>$[<\/a> ]^President<n><sg>$[ <a href='Bill Clinton'>]^Bill<np><ant><m><sg>$ ^Clinton<np><cog><sg>$[<\/a> ]^be<vbser><past><p3><sg>$ ^*criticised$ ^for<pr>$ ^frequently<adv>$ ^use<vblex><ger>$ "^*Kosova$" ^and<cnjcoo>$ ^appear<vblex><ger>$ ^to<pr>$ ^pronounce<vblex><inf>$ "^Kosovo<np><loc><sg>$" ^the<det><def><sp>$ ^Albanian<adj>$ ^way<n><sg>$^,<cm>$ ^put<vblex><ger>$ ^the<det><def><sp>$ ^emphasis<n><sg>$ ^on<pr>$ ^the<det><def><sp>$ ^*middle$ ^*syllable$ ^rather<adv>$ ^than<cnjcoo>$ ^on<pr>$ ^the<det><def><sp>$ ^first<det><ord><sp>$ ^*syllable$ ^as<pr>$ ^in<pr>$ ^the<det><def><sp>$ ^*Serbian$ ^pronunciation<n><sg>$^.<sent>$ ^This<prn><tn><mf><sg>$ ^may<vaux><inf>$^,<cm>$ ^however<adv>$^,<cm>$ ^have<vbhaver><inf>$ ^be<vbser><pp>$ ^a<det><ind><sg>$ ^simple<adj><sint>$ ^*mispronunciation$^.<sent>$^.<sent>$[][<\/p>
<p><em>]^*Rrafsh$ ^*i$ ^*Dukagjinit$[<\/em>]^,<cm>$ ^the<det><def><sp>$ "^*Dukagjin$ ^*plateau$"^.<sent>$^.<sent>$[][<\/p>
<p>]^Some<prn><tn><mf><pl>$ ^Kosovo<np><loc><sg>$ ^Albanian<n><pl>$ ^refer<vblex><inf>$ ^to<pr>$ ^Kosovo<np><loc><sg>$ ^as<cnjadv>$[ <a href='Dardania (Europe)|Dardania'>]^*Dardania$ ^(<lpar>$^Europe<np><loc><sg>$^)<rpar>$|^*Dardania$[<\/a>]^,<cm>$ ^the<det><def><sp>$ ^name<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^ancient<adj>$ ^Roman<np><ant><m><sg>$ ^province<n><sg>$ ^which<rel><an><mf><sp>$ ^cover<vblex><past>$ ^the<det><def><sp>$ ^territory<n><sg>$ ^of<pr>$ ^modern<adj>$ ^Kosovo<np><loc><sg>$ ^and<cnjcoo>$ ^part<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^Republic<n><sg>$ ^of<pr>$ ^Macedonia<np><ant><f><sg>$^.<sent>$ ^Kosovo<np><loc><sg>$ ^President<n><sg>$[ <a href='Ibrahim Rugova'>]^Ibrahim<np><ant><m><sg>$ ^*Rugova$[<\/a> ]^have<vbhaver><pri><p3><sg>$ ^be<vbser><pp>$ ^a<det><ind><sg>$ ^enthusiastic<adj>$ ^*backer$ ^of<pr>$ ^a<det><ind><sg>$ "^*Dardanian$" ^identity<n><sg>$ ^and<cnjcoo>$ ^his<det><pos><sp>$ ^flag<n><sg>$ ^and<cnjcoo>$ ^presidential<adj>$ ^seal<n><sg>$ ^refer<vblex><pres>$ ^to<pr>$ ^this<det><dem><sg>$ ^*notional$ ^identity<n><sg>$^.<sent>$ ^However<adv>$^,<cm>$ ^prpers<prn><subj><p3><nt><sg>$ ^be<vbser><pri><p3><sg>$ ^not<adv>$ ^*recognised$ ^by<pr>$ ^any<det><ind><sp>$ ^international<adj>$ ^power<n><sg>$ ^and<cnjcoo>$ ^the<det><def><sp>$ ^name<n><sg>$ "^*Kosova$" ^remain<vblex><pri><p3><sg>$ ^more<preadv>$ ^widely<adv>$ ^use<vblex><pp>$ ^among<pr>$ ^the<det><def><sp>$ ^Albanian<adj>$ ^population<n><sg>$^.<sent>$^.<sent>$[][<\/p>
<p>]^Kosovo<np><loc><sg>$ ^be<vbser><past><p3><sg>$ ^also<adv>$ ^call<vblex><pp>$ ^the<det><def><sp>$[ <em>]"^Republic<n><sg>$ ^of<pr>$ ^*Kosova$"[<\/em> ]^by<pr>$ ^the<det><def><sp>$ ^shadow<n><sg>$ ^Kosovo<np><loc><sg>$ ^Albanian<adj>$ ^government<n><sg>$ ^between<pr>$ ^a<det><ind><sg>$[ <a href='1990'>]^1990<num>$[<\/a> ]^*declaration$ ^of<pr>$ ^independence<n><sg>$ ^and<cnjcoo>$ ^the<det><def><sp>$ ^Kosovo<np><loc><sg>$ ^War<n><sg>$ ^in<pr>$ ^1999<num>$^.<sent>$ ^Only<adj>$ ^*Albania$ ^*recognised$ ^the<det><def><sp>$ ^province<n><sg>$^'s<gen>$ ^independence<n><sg>$ ^but<cnjcoo>$ ^neither<adv>$ ^*Serbia$ ^nor<cnjcoo>$ ^the<det><def><sp>$ ^international<adj>$ ^community<n><sg>$ ^follow<vblex><pp>$ ^suit<n><sg>$^.<sent>$ ^The<det><def><sp>$ "^Republic<n><sg>$ ^of<pr>$ ^*Kosova$" ^be<vbser><past><p3><sg>$ ^effectively<adv>$ ^replace<vblex><pp>$ ^by<pr>$ ^the<det><def><sp>$ ^current<adj>$ ^UN<n><acr><sg>$ ^protectorate<n><sg>$ ^follow<vblex><ger>$ ^the<det><def><sp>$ ^war<n><sg>$^.<sent>$^.<sent>$[][<\/p>
<p>]^The<det><def><sp>$ ^question<n><sg>$ ^of<pr>$ ^what<prn><itg><m><sp>$ ^to<pr>$ ^call<vblex><inf>$ ^the<det><def><sp>$ ^inhabitant<n><pl>$ ^of<pr>$ ^Kosovo<np><loc><sg>$ ^*collectively$ ^have<vbhaver><pri><p3><sg>$ ^also<adv>$ ^arouse<vblex><pp>$ ^some<det><qnt><sp>$ ^debate<n><sg>$^.<sent>$ ^Prpers<prn><subj><p3><mf><pl>$ ^have<vbhaver><pres>$ ^be<vbser><pp>$ ^call<vblex><pp>$ ^*variously$ "^*Kosovars$"^,<cm>$ "^*Kosovans$" ^and<cnjcoo>$ "^*Kosovians$"^.<sent>$ ^The<det><def><sp>$ ^two<num><sp>$ ^word<n><pl>$ ^accept<vblex><pp>$ ^by<pr>$[ <a href='Oxford English Dictionary'>]^the<det><def><sp>$ ^*Oxford$ ^English<adj>$ ^Dictionary<n><sg>$[<\/a> ]^be<vbser><pres>$ "^*Kosovar$" ^(<lpar>$^*borrowed$ ^from<pr>$ ^Albanian<n><sg>$^)<rpar>$^,<cm>$ ^the most<det><qnt><sp>$ ^widely<adv>$ ^use<vblex><pp>$ ^*variant$ ^in<pr>$ ^English<adj>$^,<cm>$ ^by<pr>$ ^a<det><ind><sg>$ ^long<adj><sint>$ ^way<n><sg>$^,<cm>$ ^and<cnjcoo>$ "^*Kosovan$" ^(<lpar>$^use<vblex><ger>$ ^the<det><def><sp>$ ^English<adj>$ ^rule<n><pl>$ ^for<pr>$[ <a href='demonym'>]^*demonyms$[<\/a>]^)<rpar>$ ^much less<adv>$ ^use<vblex><pp>$^.<sent>$ "^*Kosovian$" ^be<vbser><pri><p3><sg>$ ^consider<vblex><pp>$ ^a<det><ind><sg>$ ^non<adv>$^-<guio>$^standard<adj>$ ^word<n><sg>$ ^and<cnjcoo>$ ^very<preadv>$ ^little<adv>$ ^use<vblex><pp>$ ^at all<adv>$^.<sent>$^.<sent>$[][<\/p>
<p>]^As<cnjadv>$ ^Kosovo<np><loc><sg>$ ^have<vblex><pri><p3><sg>$ ^no<adv>$ ^formal<adj>$ ^*statehood$^,<cm>$ ^current<adj>$ ^international<adj>$ ^usage<n><sg>$ ^be<vbser><pri><p3><sg>$ ^to<pr>$ ^refer<vblex><inf>$ ^to<pr>$ ^Kosovo<np><loc><sg>$ ^*Serbs$ ^and<cnjcoo>$ ^Kosovo<np><loc><sg>$ ^Albanian<n><pl>$^.<sent>$ ^Most of<det><qnt><sp>$ ^the<det><def><sp>$ ^Albanian<adj>$^-<guio>$^descend<vblex><pp>$ ^community<n><sg>$ ^in<pr>$ ^Kosovo<np><loc><sg>$ ^would<vaux><inf>$ ^prefer<vblex><inf>$ ^the<det><def><sp>$ ^use<n><sg>$ ^of<pr>$ ^*Kosovar$ ^or<cnjcoo>$ ^*Kosovan$ ^because of<pr>$ ^the<det><def><sp>$ ^attendant<n><sg>$ ^political<adj>$ ^*overtones$^,<cm>$ ^*whilst$ ^the<det><def><sp>$ ^*Serb$ ^minority<n><sg>$ ^continue<vblex><pres>$ ^to<pr>$ ^think<vblex><inf>$ ^of<pr>$ ^themselves<prn><ref><p3><mf><pl>$ ^as<pr>$ ^*Serb$ ^or<cnjcoo>$ ^*Serbian$ ^(<lpar>$^from<pr>$ ^Kosovo<np><loc><sg>$^)<rpar>$^.<sent>$^.<sent>$[][<\/p>
<a name="Kosovo_placenames"><\/a><h3>]^Kosovo<np><loc><sg>$ ^*placenames$^.<sent>$[][<\/h3><p>]^Most<det><qnt><sp>$ ^*localities$ ^in<pr>$ ^Kosovo<np><loc><sg>$ ^have<vblex><pres>$ ^distinct<adj>$ ^Albanian<n><sg>$ ^*placenames$^.<sent>$^.<sent>$[][<\/p>
<p>]^Since<pr>$ ^the<det><def><sp>$ ^Unite<vblex><pp>$ ^Nation<n><pl>$ ^take<vblex><past>$ ^over<pr>$ ^administration<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^province<n><sg>$ ^in<pr>$ ^June<n><sg>$ ^1999<num>$^\]<rpar>$^.<sent>$^.<sent>$[][<\/p>
<a name="Flag"><\/a><h2>]^Flag<n><sg>$^.<sent>$[][<\/h2><p>]^The<det><def><sp>$ ^province<n><sg>$ ^never<adv>$ ^have<vblex><past>$ ^a<det><ind><sg>$ ^official<adj>$ ^flag<n><sg>$ ^of<pr>$ ^its<det><pos><sp>$ ^own<adj>$^.<sent>$ ^The<det><def><sp>$[ <a href='Flag of Albania|Albanian flag'>]^Flag<n><sg>$ ^of<pr>$ ^*Albania$|^Albanian<adj>$ ^flag<n><sg>$[<\/a> ]^be<vbser><pri><p3><sg>$ ^use<vblex><pp>$ ^by<pr>$ ^the<det><def><sp>$ ^Albanian<adj>$^-<guio>$^dominate<vblex><pp>$ ^administration<n><sg>$ ^and<cnjcoo>$ ^the<det><def><sp>$ ^vast<adj><sint>$ ^majority<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$ ^Albanian<n><pl>$^.<sent>$ ^Kosovo<np><loc><sg>$^'s<gen>$ ^president<n><sg>$^,<cm>$ ^Ibrahim<np><ant><m><sg>$ ^*Rugova$^,<cm>$ ^have<vbhaver><pri><p3><sg>$ ^propose<vblex><pp>$ ^a<det><ind><sg>$ ^alternative<adj>$ ^flag<n><sg>$ ^of<pr>$ "^*Dardania$" ^base<vblex><pp>$ ^on<pr>$ ^the<det><def><sp>$ ^design<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^Albanian<adj>$ ^flag<n><sg>$^,<cm>$ ^but<cnjcoo>$ ^even<adv>$ ^within<pr>$ ^Kosovo<np><loc><sg>$ ^prpers<prn><subj><p3><nt><sg>$ ^be<vbser><pri><p3><sg>$ ^little<adv>$ ^use<vblex><pp>$^.<sent>$ == ^History<n><sg>$ ==^.<sent>$[][<\/p>
<p><em>]^See<vblex><pres>$[ <a href='History of Kosovo'>]^History<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$[<\/a>]^.<sent>$^.<sent>$[][<\/em><\/p>
<a name="Politics_and_international_status"><\/a><h2>]^Politics<n><sg>$ ^and<cnjcoo>$ ^international<adj>$ ^status<n><sg>$^.<sent>$[][<\/h2><p>]{{^Politics<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$}}[
]^Kosovo<np><loc><sg>$^'s<gen>$ ^international<adj>$ ^status<n><sg>$ ^be<vbser><pri><p3><sg>$ ^anomalous<adj>$ ^in<adv>$ ^that<cnjsub>$ ^although<cnjadv>$ ^prpers<prn><subj><p3><nt><sg>$ ^be<vbser><pri><p3><sg>$ ^formally<adv>$ ^a<det><ind><sg>$ ^province<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^Republic<n><sg>$ ^of<pr>$ ^*Serbia$^,<cm>$ ^actual<adj>$ ^administration<n><sg>$ ^be<vbser><pri><p3><sg>$ ^*presently$ ^conduct<vblex><pp>$ ^by<pr>$[ <a href='United Nations'>]^the<det><def><sp>$ ^Unite<vblex><pp>$ ^Nation<n><pl>$[<\/a> ]^with<pr>$ ^no<det><ind><sg>$ ^involvement<n><sg>$ ^on<pr>$ ^the<det><def><sp>$ ^part<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^*Serbian$ ^government<n><pl>$ ^(<lpar>$^under<pr>$ ^Security<n><sg>$ ^Council<n><sg>$ ^resolution<n><sg>$ ^1244<num>$ ^of<pr>$[ <a href='10 June'>]^10<num>$ ^June<n><sg>$[<\/a> <a href='1999'>]^1999<num>$[<\/a>]^;<sent>$ ^see<vblex><pres>$[ <a href='http:\/\/www.un.org\/Docs\/scres\/1999\/sc99.htm Security Council Resolutions 1999'>]^1<num>$[<\/a>]^)<rpar>$^.<sent>$[  ]^The<det><def><sp>$ ^government<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^province<n><sg>$ ^be<vbser><pri><p3><sg>$ ^the<det><def><sp>$ ^responsibility<n><sg>$ ^of<pr>$ ^the<det><def><sp>$[ <a href='United Nations Mission in Kosovo'>]^Unite<vblex><pp>$ ^Nation<n><pl>$ ^Mission<n><sg>$ ^in<pr>$ ^Kosovo<np><loc><sg>$[<\/a> ]^(<lpar>$^*UNMIK$^)<rpar>$^.<sent>$ ^Under<pr>$ ^the<det><def><sp>$ ^term<n><pl>$ ^of<pr>$ ^the<det><def><sp>$[ <a href='Kumanovo agreement'>]^*Kumanovo$ ^agreement<n><sg>$[<\/a> ]^and<cnjcoo>$ ^subsequent<adj>$ ^UN<n><acr><sg>$[ <a href='Security Council'>]^Security<n><sg>$ ^Council<n><sg>$[<\/a> <a href='Resolution 1244'>]^Resolution<n><sg>$ ^1244<num>$[<\/a>]^,<cm>$ ^which<prn><itg><m><sp>$ ^end<vblex><past>$ ^the<det><def><sp>$[ <a href='Kosovo War'>]^Kosovo<np><loc><sg>$ ^War<n><sg>$[<\/a>]^,<cm>$ ^security<n><sg>$ ^be<vbser><pri><p3><sg>$ ^provide<vblex><pp>$ ^by<pr>$ ^the<det><def><sp>$ ^Kosovo<np><loc><sg>$ ^Force<n><sg>$ ^(<lpar>$^*KFOR$^)<rpar>$^,<cm>$ ^which<prn><itg><m><sp>$ ^be<vbser><pri><p3><sg>$ ^lead<vblex><pp>$ ^by<pr>$[ <a href='NATO'>]^NATO<n><acr><sg>$[<\/a> ]^and<cnjcoo>$ ^be<vbser><pri><p3><sg>$ ^*answerable$ ^to<pr>$ ^*UNMIK$^.<sent>$^.<sent>$[][<\/p>
<p>]^*UNMIK$ ^have<vblex><pri><p3><sg>$ ^so<preadv>$ ^far<adv>$ ^establish<vblex><pp>$ ^a<det><ind><sg>$ ^provisional<adj>$ ^assembly<n><sg>$^,<cm>$ ^provisional<adj>$ ^government<n><sg>$ ^and<cnjcoo>$ ^the<det><def><sp>$ ^office<n><sg>$ ^of<pr>$ ^provisional<adj>$ ^president<n><sg>$^,<cm>$ ^which<prn><itg><m><sp>$ ^be<vbser><pres>$ ^legislative<adj>$ ^and<cnjcoo>$ ^executive<adj>$ ^body<n><pl>$ ^under<pr>$ ^*UNMIK$^'s<gen>$ ^control<n><sg>$^.<sent>$ ^Control<n><sg>$ ^of<pr>$ ^security<n><sg>$^,<cm>$ ^justice<n><sg>$ ^and<cnjcoo>$ ^external<adj>$ ^affair<n><pl>$ ^be<vbser><pres>$ ^still<adv>$ ^under<pr>$ ^full<adj><sint>$ ^*UNMIK$ ^control<n><sg>$^.<sent>$ ^The<det><def><sp>$[ <a href='Assembly of Kosovo'>]^Assembly<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$[<\/a> ]^be<vbser><past><p3><sg>$ ^elect<vblex><pp>$ ^in<pr>$ ^November<n><sg>$[ <a href='2001'>]^2001<num>$[<\/a> ]^and<cnjcoo>$[ <a href='Ibrahim Rugova'>]^Ibrahim<np><ant><m><sg>$ ^*Rugova$[<\/a> ]^be<vbser><past><p3><sg>$ ^elect<vblex><pp>$ ^as<pr>$ ^president<n><sg>$ ^in<pr>$ ^March<n><sg>$[ <a href='2002'>]^2002<num>$[<\/a>]^.<sent>$ ^The<det><def><sp>$ ^seat<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^assembly<n><sg>$^,<cm>$ ^government<n><sg>$ ^and<cnjcoo>$ ^president<n><sg>$ ^be<vbser><pri><p3><sg>$ ^in<pr>$[ <a href='Pristina'>]^*Pristina$[<\/a>]^.<sent>$ ^So<preadv>$ ^far<adv>$^,<cm>$ ^the<det><def><sp>$ ^parliament<n><sg>$ ^have<vbhaver><pri><p3><sg>$ ^*enacted$ ^and<cnjcoo>$ ^*UNMIK$ ^approve<vblex><past>$ ^a<det><ind><sg>$ ^constitutional<adj>$ ^framework<n><sg>$^,<cm>$ ^customs<n><pl>$ ^code<n><sg>$^,<cm>$ ^and<cnjcoo>$ ^two<num><sp>$ ^*criminal$ ^code<n><pl>$^.<sent>$^.<sent>$[][<\/p>
<p>]^*UNMIK$ ^be<vbser><pri><p3><sg>$ ^issue<vblex><ger>$ ^travel<n><sg>$ ^document<n><pl>$ ^which<rel><an><mf><sp>$ ^serve<vblex><inf>$ ^instead of<pr>$[ <a href='passport'>]^passport<n><pl>$[<\/a> ]^in<pr>$ ^country<n><pl>$ ^which<rel><an><mf><sp>$ ^be<vbser><pres>$ ^accept<vblex><ger>$ ^to<pr>$ ^*recognise$ ^prpers<prn><obj><p3><mf><pl>$ ^as<pr>$ ^such<det><ind><sp>$^;<sent>$ ^*UNMIK$ ^be<vbser><pri><p3><sg>$ ^also<adv>$ ^issue<vblex><ger>$ ^identity<n><sg>$ ^card<n><pl>$ ^and<cnjcoo>$ ^car<n><sg>$ ^plate<n><pl>$^,<cm>$ ^which<prn><itg><m><sp>$ ^again<adv>$ ^be<vbser><pres>$ ^valid<adj>$ ^only<adv>$ ^in<pr>$ ^country<n><pl>$ ^which<rel><an><mf><sp>$ ^be<vbser><pres>$ ^accept<vblex><ger>$ ^prpers<prn><obj><p3><mf><pl>$ ^as<pr>$ ^such<det><ind><sp>$^.<sent>$ ^Kosovo<np><loc><sg>$^'s<gen>$ ^postal<adj>$ ^system<n><sg>$ ^be<vbser><pri><p3><sg>$ ^also<adv>$ ^*usable$ ^only<adv>$ ^in<pr>$ ^country<n><pl>$ ^which<rel><an><mf><sp>$ ^be<vbser><pres>$ ^accept<vblex><ger>$ ^to<pr>$ ^*recognise$ ^prpers<prn><obj><p3><nt><sg>$ ^as<pr>$ ^such<det><ind><sp>$ ^(<lpar>$^letter<n><pl>$ ^address<vblex><pp>$ ^to<pr>$ ^Kosovo<np><loc><sg>$ ^only<adv>$^,<cm>$ ^or<cnjcoo>$ ^to<pr>$ ^*Serbia$ ^and<cnjcoo>$ ^Montenegro<np><loc><sg>$ ^have<vblex><pres>$ ^a<det><ind><sg>$ ^chance<n><sg>$ ^of<pr>$ ^not<adv>$ ^arrive<vblex><ger>$^;<sent>$ ^the<det><def><sp>$ ^Universal<adj>$ ^Postal<adj>$ ^Union<n><sg>$ ^advise<vblex><pri><p3><sg>$ ^correspondent<n><pl>$ ^to<pr>$ ^use<vblex><inf>$ "^Kosovo<np><loc><sg>$ ^(<lpar>$^*UNMIK$^)<rpar>$" ^as<cnjadv>$ ^the<det><def><sp>$ ^address<n><sg>$[ <a href='http:\/\/www.upu.int\/post_code\/en\/countries\/KOS.pdf'>]^2<num>$[<\/a>]^)<rpar>$^.<sent>$^.<sent>$[][<\/p>
<p>]^*UNMIK$ ^have<vbhaver><pri><p3><sg>$ ^also<adv>$ ^create<vblex><pp>$ ^a<det><ind><sg>$ ^police<adj>$ ^force<n><sg>$ ^(<lpar>$^the<det><def><sp>$[ <a href='Kosovo Police Service'>]^Kosovo<np><loc><sg>$ ^Police<adj>$ ^Service<n><sg>$[<\/a>]^)<rpar>$ ^with<pr>$ ^employee<n><pl>$ ^from<pr>$ ^all<predet><sp>$ ^ethnic<adj>$ ^community<n><pl>$ ^(<lpar>$^Albanian<n><sg>$^,<cm>$ ^*Serbian$^,<cm>$ ^*Roma$^,<cm>$ ^*Bosniac$^,<cm>$ ^*Roma$^,<cm>$ ^*etc$^)<rpar>$^,<cm>$ ^and<cnjcoo>$ ^manage<vblex><pri><p3><sg>$ ^the<det><def><sp>$ ^province<n><sg>$^'s<gen>$ ^railway<n><pl>$ ^and<cnjcoo>$ ^*airline$ ^(<lpar>$[<a href='Kosova Airlines'>]^*Kosova$ ^*Airlines$[<\/a>]^)<rpar>$^.<sent>$ ^The<det><def><sp>$ ^*airspace$ ^of<pr>$ ^the<det><def><sp>$ ^province<n><sg>$ ^be<vbser><pri><p3><sg>$ ^control<vblex><pp>$ ^by<pr>$ ^*KFOR$^.<sent>$ ^*UNMIK$ ^use<vblex><pri><p3><sg>$ ^the<det><def><sp>$ ^Unite<vblex><pp>$ ^Nation<n><pl>$ ^flag<n><sg>$^.<sent>$^.<sent>$[][<\/p>
<p>]^The<det><def><sp>$ ^Constitutional<adj>$ ^Framework<n><sg>$ ^*enacted$ ^by<pr>$ ^the<det><def><sp>$ ^Kosovo<np><loc><sg>$ ^assembly<n><sg>$ ^(<lpar>$^with<pr>$ ^*UNMIK$ ^approval<n><sg>$^)<rpar>$ ^have<vbhaver><pri><p3><sg>$ ^adopt<vblex><pp>$ ^a<det><ind><sg>$ ^policy<n><sg>$ ^of<pr>$[ <a href='affirmative action'>]^affirmative<adj>$ ^action<n><sg>$[<\/a> ]^in<pr>$ ^the<det><def><sp>$ ^assembly<n><sg>$ ^to<pr>$ ^ensure<vblex><inf>$ ^that<cnjsub>$ ^the<det><def><sp>$ ^province<n><sg>$^'s<gen>$ ^minority<n><pl>$ ^be<vbser><pres>$ ^properly<adv>$ ^represent<vblex><pp>$^.<sent>$ ^Out of<pr>$ ^120<num>$ ^seat<n><pl>$^,<cm>$ ^10<num>$ ^be<vbser><pres>$ ^reserve<vblex><pp>$ ^for<pr>$ ^*Serbs$ ^and<cnjcoo>$ ^another<prn><tn><m><sg>$ ^10<num>$ ^for<cnjadv>$ ^non<adv>$^-<guio>$^Albanian<adj>$ ^minority<n><pl>$^,<cm>$ ^while<cnjadv>$ ^the<det><def><sp>$ ^remain<vblex><ger>$ ^100<num>$ ^seat<n><pl>$ ^be<vbser><pres>$ ^elect<vblex><pp>$ ^through<pr>$ ^direct<adj>$ ^vote<vblex><ger>$^.<sent>$^.<sent>$[][<\/p>
<p>]^Its<det><pos><sp>$ ^final<adj>$ ^status<n><sg>$ ^have<vbhaver><pri><p3><sg>$ ^not<adv>$ ^yet<adv>$ ^be<vbser><pp>$ ^resolve<vblex><pp>$^,<cm>$ ^though<cnjadv>$ ^talk<n><pl>$ ^on<pr>$ ^the<det><def><sp>$ ^subject<n><sg>$ ^be<vbser><pres>$ ^plan<vblex><pp>$ ^for<pr>$ ^later<adv>$ ^in<pr>$ ^2005<num>$^,<cm>$ ^and<cnjcoo>$ ^considerable<adj>$ ^difficulty<n><pl>$ ^lie<n><sg>$ ^ahead<adv>$ ^in<pr>$ ^*reconciling$ ^the<det><def><sp>$ ^apparently<adv>$ ^incompatible<adj>$ ^position<n><pl>$ ^of<pr>$ ^the<det><def><sp>$ ^*Serbian$ ^and<cnjcoo>$ ^Albanian<adj>$ ^side<n><pl>$^.<sent>$ ^The<det><def><sp>$ ^Albanian<n><pl>$ ^reject<vblex><inf>$ ^*Serbian$ ^sovereignty<n><sg>$^;<sent>$ ^although<cnjadv>$ ^the<det><def><sp>$ ^fall<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^*Milosevic$ ^government<n><sg>$ ^have<vbhaver><pri><p3><sg>$ ^ease<vblex><pp>$ ^some<prn><tn><mf><pl>$ ^of<pr>$ ^the<det><def><sp>$ ^political<adj>$ ^tension<n><pl>$ ^between<pr>$ ^the<det><def><sp>$ ^two<num><sp>$ ^administration<n><pl>$^,<cm>$ ^most<preadv>$ ^Kosovo<np><loc><sg>$ ^Albanian<n><pl>$ ^do<vbdo><pres>$ ^not<adv>$ ^believe<vblex><inf>$ ^that<cnjsub>$ ^the<det><def><sp>$ ^*Serbian$ ^side<n><sg>$ ^will<vaux><inf>$ ^respect<vblex><inf>$ ^Albanian<adj>$ ^right<n><pl>$^.<sent>$^.<sent>$[][<\/p>
<a name="Administrative_subdivisions"><\/a><h2>]^Administrative<adj>$ ^*subdivisions$^.<sent>$[][<\/h2><p>]^Administrative<adj>$ ^*subdivisions$ ^in<pr>$ ^Kosovo<np><loc><sg>$ ^be<vbser><pres>$ ^know<vblex><pp>$ ^as<pr>$ ^*komuna$^.<sent>$^.<sent>$[][<\/p>
<a name="Currency"><\/a><h2>]^Currency<n><sg>$^.<sent>$[][<\/h2><p><a href='UNMIK'>]^*UNMIK$[<\/a> ]^declare<vblex><past>$ ^the<det><def><sp>$[ <a href='euro'>]^euro<n><sg>$[<\/a> ]^to<pr>$ ^be<vbser><inf>$ ^official<adj>$ ^currency<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^province<n><sg>$ ^in<pr>$[ <a href='2001'>]^2001<num>$[<\/a> ]^in<pr>$ ^the<det><def><sp>$ ^course<n><sg>$ ^of<pr>$ ^implement<vblex><ger>$ ^a<det><ind><sg>$ ^currency<n><sg>$ ^reform<n><sg>$^.<sent>$ ^This<prn><tn><mf><sg>$ ^be<vbser><past><p3><sg>$ ^undertake<vblex><pp>$ ^to<pr>$ ^replace<vblex><inf>$ ^the<det><def><sp>$ ^previous<adj>$ ^*widespread$ ^use<n><sg>$ ^of<pr>$ ^the<det><def><sp>$[ <a href='Deutschmark'>]^*Deutschmark$[<\/a>]^,<cm>$ ^which<prn><itg><m><sp>$ ^have<vbhaver><past>$ ^become<vblex><pp>$[ <em>]^*de$[<\/em> ]^*facto$ ^currency<n><sg>$ ^even<adv>$ ^before<pr>$ ^the<det><def><sp>$ ^1999<num>$ ^war<n><sg>$^.<sent>$^.<sent>$[][<\/p>
<a name="Demographics"><\/a><h2>]^*Demographics$^.<sent>$[][<\/h2><p><em>]^Main<adj>$ ^article<n><sg>$^:<sent>$[ <a href='Demographic history of Kosovo'>]^*Demographic$ ^history<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$^.<sent>$[][<\/a><\/em><\/p>
<p><a href='Albanians'>]^Albanian<n><pl>$[<\/a> ]^comprise<vblex><inf>$ ^a<det><ind><sg>$ ^almost<adv>$ ^90%<num><percent>$ ^majority<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^population<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^province<n><sg>$^.<sent>$ ^Their<det><pos><sp>$ ^percentage<n><sg>$ ^as a<pr>$ ^proportion<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^province<n><sg>$^'s<gen>$ ^population<n><sg>$ ^have<vbhaver><pri><p3><sg>$ ^increase<vblex><pp>$ ^steadily<adv>$ ^over<pr>$ ^time<n><sg>$ ^as a result of<pr>$ ^a<det><ind><sg>$ ^high<adj><sint>$ ^birth<n><sg>$ ^rate<n><sg>$^,<cm>$ ^immigration<n><sg>$ ^from<pr>$[ <a href='Albania'>]^*Albania$[<\/a> ]^and<cnjcoo>$ ^*concentrion$ ^of<pr>$ ^Albanian<n><pl>$ ^from<pr>$ ^area<n><pl>$ ^formerly<adv>$ ^under<pr>$ ^the<det><def><sp>$ ^*Sandjak$ ^of<pr>$ ^*Nish$^,<cm>$ ^*southern$ ^*Serbia$^.<sent>$ ^Most of<det><qnt><sp>$ ^the<det><def><sp>$ ^province<n><sg>$^'s<gen>$ ^Albanian<adj>$ ^population<n><sg>$ ^become<vblex><past>$ ^*refugees$ ^during<pr>$ ^the<det><def><sp>$ ^war<n><sg>$ ^but<cnjcoo>$ ^quickly<adv>$ ^return<vblex><pp>$ ^to<pr>$ ^their<det><pos><sp>$ ^home<n><pl>$ ^at<pr>$ ^its<det><pos><sp>$ ^end<n><sg>$^.<sent>$^.<sent>$[][<\/p>
<p> 
]^According to<pr>$ ^the<det><def><sp>$ ^2000<num>$ ^Living<adj>$ ^Standard<adj>$ ^Measurement<n><sg>$ ^Survey<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^Statistical<adj>$ ^Office<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$[<a href='http:\/\/www.sok-kosovo.org\/pdf\/population\/Kosovo_population.pdf'>]^3<num>$[<\/a>]^,<cm>$ ^Kosovo<np><loc><sg>$^'s<gen>$ ^total<adj>$ ^population<n><sg>$ ^be<vbser><pri><p3><sg>$ ^approximately<adv>$ ^1,970<num>$^,<cm>$^000<num>$ ^with<pr>$ ^the<det><def><sp>$ ^follow<vblex><ger>$ ^ethnic<adj>$ ^proportion<n><pl>$^:<sent>$^.<sent>$[][<\/p>
<ul>
<li>]^88%<num><percent>$ ^Albanian<n><pl>$ ^(<lpar>$^1,733<num>$^,<cm>$^600<num>$^)<rpar>$^.<sent>$[][<\/li>
<li> 
]^7%<num><percent>$ ^*Serbs$ ^(<lpar>$^137,900<num>$^)<rpar>$^.<sent>$[][<\/li>
<li> 
]^1.9%<num><percent>$ ^Muslim<n><sg>$ ^*Slavs$ ^(<lpar>$^37,400<num>$^)<rpar>$^.<sent>$[][<\/li>
<li> 
]^1.7%<num><percent>$ ^*Roma$ ^(<lpar>$^33,500<num>$^)<rpar>$^.<sent>$[][<\/li>
<li> 
]^1%<num><percent>$ ^*Turks$ ^(<lpar>$^19,700<num>$^)<rpar>$^.<sent>$[][<\/li>
<\/ul>
<p><br\/>
<\/p>
<a name="See_also"><\/a><h2>]^See<vblex><pres>$ ^also<adv>$^.<sent>$[][<\/h2><ul>
<li><a href='Assembly of Kosovo'>]^Assembly<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$^.<sent>$[][<\/a><\/li>
<li><a href='Government of Kosovo'>]^Government<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$^.<sent>$[][<\/a><\/li>
<li><a href='Prime Minister of Kosovo'>]^Prime<adj>$ ^Minister<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$^.<sent>$[][<\/a><\/li>
<li><a href='President of Kosovo'>]^President<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$^.<sent>$[][<\/a><\/li>
<li><a href='Battle of Kosovo|Battle of Kosovo (1389)'>]^Battle<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$|^Battle<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$ ^(<lpar>$^1389<num>$^)<rpar>$^.<sent>$[][<\/a><\/li>
<li>   
<a href='National awakening and the birth of Albania'>]^National<adj>$ ^awaken<vblex><ger>$ ^and<cnjcoo>$ ^the<det><def><sp>$ ^birth<n><sg>$ ^of<pr>$ ^*Albania$^.<sent>$[][<\/a><\/li>
<li><a href='Unrest in Kosovo'>]^Unrest<n><sg>$ ^in<pr>$ ^Kosovo<np><loc><sg>$[<\/a> ]^(<lpar>$^about<pr>$ ^the<det><def><sp>$ ^March<n><sg>$ ^2004<num>$ ^unrest<n><sg>$^)<rpar>$^.<sent>$[][<\/li>
<\/ul>
<p><br\/>
<\/p>
<a name="External_links"><\/a><h2>]^External<adj>$ ^link<n><pl>$^.<sent>$[][<\/h2><ul>
<li><a href='http:\/\/www.lib.utexas.edu\/maps\/kosovo.html Kosovo maps from the Perry-CastaÃ±eda Library Map Collection'>]^4<num>$^.<sent>$[][<\/a><\/li>
<li><a href='http:\/\/www.chmouel.com\/geeklog\/gallery\/gallery_individual.php\/mkosovo\/ A collection of photos from Kosovo'>]^5<num>$^.<sent>$[][<\/a><\/li>
<li><a href='http:\/\/www.kosovo.com\/sk\/history\/kosovo_origins\/default.htm  Hugo Roth, <em>]^Kosovo<np><loc><sg>$ ^Origin<n><pl>$[<\/em>]^'<apos>$[>]^6<num>$[<\/a>]^:<sent>$ ^a<det><ind><sg>$ ^historian<n><sg>$^'s<gen>$ ^objective<adj>$ ^comprehensive<adj>$ ^*overview$^.<sent>$[][<\/li>
<\/ul>
<p><br\/>
]===^Provisional<adj>$ ^Institution<n><pl>$ ^of<pr>$ ^*Self$^-<guio>$^Government<n><sg>$===^.<sent>$[][<\/p>
<ul>
<li>  
<a href='http:\/\/www.assembly-kosova.org\/ Assembly of Kosovo'>]^7<num>$^.<sent>$[][<\/a><\/li>
<li>  
<a href='http:\/\/www.pm-ksgov.net\/ Kosovo Prime Minister'>]^8<num>$^.<sent>$[][<\/a><\/li>
<\/ul>
<p><br\/>
<\/p>
<a name="Pro-Albanian"><\/a><h3>]^*Pro$^-<guio>$^Albanian<n><sg>$^.<sent>$[][<\/h3><ul>
<li><a href='http:\/\/www.albeu.com Albanian National Portal, latest news from kosovo, albania and macedonia.'>]^9<num>$^.<sent>$[][<\/a><\/li>
<li><a href='http:\/\/www.kosova.com Kosova Information Center (in Albanian)'>]^10<num>$^.<sent>$[][<\/a><\/li>
<li><a href='http:\/\/www.kosovapress.com Kosovapress - Kosovo news agency'>]^11<num>$^.<sent>$[][<\/a><\/li>
<li><a href='http:\/\/www.rtklive.com  Radio Television of Kosova (news in Albanian, Serbian and English)'>]^12<num>$^.<sent>$[][<\/a><\/li>
<li><a href='http:\/\/beqiraj.com\/kosova\/de\/ General information from Beqiraj.com'>]^13<num>$[<\/a> ]^(<lpar>$^in<pr>$ ^German<adj>$^)<rpar>$^.<sent>$[][<\/li>
<li><a href='http:\/\/beqiraj.com\/kosova\/al\/ General information from Beqiraj.com'>]^14<num>$[<\/a> ]^(<lpar>$^in<pr>$ ^Albanian<n><sg>$^)<rpar>$^.<sent>$[][<\/li>
<li><a href='http:\/\/www.albanian.com\/main\/countries\/kosova General information from Albanian.com'>]^15<num>$^.<sent>$[][<\/a><\/li>
<li><a href='http:\/\/www.alb-net.com\/warcrimes-img\/warcrimes.htm Kosovo Crisis Center - Serbian Massacres of Albanians'>]^16<num>$^.<sent>$[][<\/a><\/li>
<\/ul>
<\/body>
<\/html>
]