^.<sent>$[][
<!DOCTYPE html PUBLIC "-\/\/W3C\/\/DTD HTML 3.2\/\/EN">
<html>
<head>
<meta name="generator" content=
"media wiki xml converter. copyright James Michael DuPont 2009">
<title><\/title>
<\/head>
<body>
    <h1><\/h1>
<p>
]{|[ 
]|+[&lt;]^big<adj><sint>$[&gt;&lt;]^big<adj><sint>$[&gt;<strong> ]^Kosovo<np><loc><sg>$[ <\/strong>&lt;]^*br$\/[&gt;<strong>]ÐÐ¾^*Ñ$Ð¾Ð²Ð¾ Ð¸ ÐÐµ^*Ñ$Ð¾^*Ñ$Ð¸^*Ñ$Ð°[<\/strong>&lt;]^*br$\/[&gt;]^'<apos>$^'<apos>$^'<apos>$^*Kosova$[ &lt;]\/^big<adj><sint>$[&gt;&lt;]\/^big<adj><sint>$[&gt;
]| ^*align$=^centre<n><sg>$ |[ <a href='Image:SerbiaMontenegro-Kosovo3.png'>]^Image<n><sg>$^:<sent>$^*SerbiaMontenegro$^-<guio>$^Kosovo<np><loc><sg>$^3<num>$^.<sent>$^*png$[<\/a>
]| {{^*Serbia$ ^and<cnjcoo>$ ^Montenegro<np><loc><sg>$ ^2<num>$}}[
]|^-<guio>$[
]|[ <a href='Official language'>]^Official<adj>$ ^language<n><pl>$[<\/a>
]|[ <a href='English language|English'>]^English<adj>$ ^language<n><sg>$|^English<adj>$[<\/a>]^,<cm>$[ <a href='Albanian language|Albanian'>]^Albanian<adj>$ ^language<n><sg>$|^Albanian<n><sg>$[<\/a>]^,<cm>$[ <a href='Serbian language|Serbian'>]^*Serbian$ ^language<n><sg>$|^*Serbian$[<\/a>
]|^-<guio>$[
]|[ <a href='Capital'>]^Capital<adj>$[<\/a>
]|[ <a href='PriÅ¡tina'>]^*Pri$Å^¡<lquest>$^*tina$[<\/a>
]|^-<guio>$[
]|[ <a href='President of Kosovo|President'>]^President<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$|^President<n><sg>$[<\/a>
]|^Acting<adj>$ ^President<n><sg>$[ <a href='Nexhat Daci'>]^*Nexhat$ ^*Daci$[<\/a>
]|^-<guio>$[
]|[ <a href='Prime Minister of Kosovo|Prime Minister'>]^Prime<adj>$ ^Minister<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$|^Prime<adj>$ ^Minister<n><sg>$[<\/a>
]|[ <a href='Bajram Kosumi'>]^*Bajram$ ^*Kosumi$[<\/a>
]|^-<guio>$[
]|[ <a href='Area'>]^Area<n><sg>$[<\/a>&lt;]^*br$\/[&gt;&amp;]^*nbsp$^;<sent>$[&amp;]^*ndash$^;<sent>$ ^Total<n><sg>$[&lt;]^*br$\/[&gt;&amp;]^*nbsp$^;<sent>$[&amp;]^*ndash$^;<sent>$ % ^water<n><sg>$[
]|[ &lt;]^*br$\/[&gt;&amp;]^*nbsp$^;<sent>$[<a href='1 E10 mÂ²|10,887'>]^1<num>$ ^*E$^10<num>$ ^*mÂ$²|^10,887<num>$[<\/a> ]^*kmÂ$²[&lt;]^*br$\/[&gt;&amp;]^*nbsp$^;<sent>$^*n$\/^a<det><ind><sg>$[
]|^-<guio>$[
]| ^*valign$=^top<adj>$ |[ <a href='Population'>]^Population<n><sg>$[<\/a>&lt;]^*br$\/[&gt;&amp;]^*nbsp$^;<sent>$[&amp;]^*ndash$^;<sent>$ ^Total<n><sg>$ ^(<lpar>$[<a href='2003'>]^2003<num>$[<\/a>]^)<rpar>$[&lt;]^*br$\/[&gt;&amp;]^*nbsp$^;<sent>$[&amp;]^*ndash$^;<sent>$[ <a href='Population density|Density'>]^Population<n><sg>$ ^density<n><sg>$|^Density<n><sg>$[<\/a>&lt;]^*br$\/[&gt;
]|[ &lt;]^*br$\/[&gt;&amp;]^*nbsp$^;<sent>$^2.4<num>$ ^million<num><sp>$ ^(<lpar>$^*est$^.<sent>$^)<rpar>$[&lt;]^*br$\/[&gt;&amp;]^*nbsp$^;<sent>$^185<num>$\/^*kmÂ$² ^(<lpar>$^*approx$^)<rpar>$[
]|^-<guio>$[
]| ^*valign$=^top<adj>$ |[ <a href='List of ethnic groups|Ethnic groups'>]^List<n><sg>$ ^of<pr>$ ^ethnic<adj>$ ^group<n><pl>$|^Ethnic<adj>$ ^group<n><pl>$[<\/a>&lt;]^*br$\/[&gt;]^(<lpar>$[<a href='2003'>]^2003<num>$[<\/a>]^)<rpar>$[
]|[ <a href='Albanians'>]^Albanian<n><pl>$[<\/a>]^:<sent>$ ^88%<num><percent>$[&lt;]^*br$\/[&gt;<a href='Serbs'>]^*Serbs$[<\/a>]^:<sent>$ ^7%<num><percent>$[&lt;]^*br$\/[&gt;]^Others<prn><tn><mf><pl>$^:<sent>$ ^5%<num><percent>$[
]|^-<guio>$[
]|[ <a href='Time zone'>]^Time<n><sg>$ ^zone<n><sg>$[<\/a>
]|[ <a href='UTC'>]^*UTC$[<\/a> ]+^1<num>$[
]|^-<guio>$^.<sent>$[][<\/p>
<p>]|^*colspan$=^2<num>$|[ <a href='Turkish language|Turkish'>]^Turkish<adj>$ ^language<n><sg>$|^Turkish<adj>$[<\/a> ]^at<pr>$ ^local<adj>$ ^level<n><pl>$[
]|}^.<sent>$[][<\/p>
<p><strong>]^Kosovo<np><loc><sg>$[<\/strong> ]^(<lpar>$[<a href='Serbian language|Serbian'>]^*Serbian$ ^language<n><sg>$|^*Serbian$[<\/a>]^:<sent>$ ÐÐ¾^*Ñ$Ð¾Ð²Ð¾ Ð¸ ÐÐµ^*Ñ$Ð¾^*Ñ$Ð¸^*Ñ$Ð° \/[ <em>]^Kosovo<np><loc><sg>$ ^*i$ ^*Metohija$[<\/em>]^,<cm>$[ <a href='Albanian language|Albanian'>]^Albanian<adj>$ ^language<n><sg>$|^Albanian<n><sg>$[<\/a>]^:<sent>$[ <em>]^*Kosov$Ã«[<\/em> ]\/[ <em>]^*Kosova$[<\/em>]^)<rpar>$ ^be<vbser><pri><p3><sg>$ ^a<det><ind><sg>$ ^province<n><sg>$ ^of<pr>$[ <a href='Serbia'>]^*Serbia$[<\/a>]^.<sent>$ ^Prpers<prn><subj><p3><nt><sg>$ ^be<vbser><pri><p3><sg>$ ^the<det><def><sp>$ ^subject<n><sg>$ ^of<pr>$ ^a<det><ind><sg>$ ^ongoing<adj>$ ^territorial<adj>$ ^dispute<n><sg>$ ^between<pr>$ ^*Serbia$ ^and<cnjcoo>$ ^the<det><def><sp>$ ^province<n><sg>$^'s<gen>$ ^majority<n><sg>$ ^ethnic<adj>$[ <a href='Albanians|Albanian'>]^Albanian<n><pl>$|^Albanian<adj>$[<\/a> ]^population<n><sg>$^.<sent>$ ^Prpers<prn><obj><p3><nt><sg>$ ^lie<n><pl>$ ^within<pr>$ ^*Serbia$^'s<gen>$ ^traditional<adj>$ ^border<n><pl>$ ^inside<pr>$ ^the<det><def><sp>$[ <a href='Serbian-Montenegrin'>]^*Serbian$^-<guio>$^*Montenegrin$[<\/a> ]^federation<n><sg>$^,<cm>$ ^but<cnjcoo>$ ^since<pr>$ ^the<det><def><sp>$[ <a href='Kosovo War'>]^Kosovo<np><loc><sg>$ ^War<n><sg>$[<\/a> ]^prpers<prn><subj><p3><nt><sg>$ ^have<vbhaver><pri><p3><sg>$ ^be<vbser><pp>$ ^administer<vblex><pp>$ ^by<pr>$[ <a href='United Nations'>]^the<det><def><sp>$ ^Unite<vblex><pp>$ ^Nation<n><pl>$[<\/a> ]^under<pr>$ ^the<det><def><sp>$ ^auspice<n><pl>$ ^of<pr>$[ <a href='UNMIK'>]^*UNMIK$[<\/a>]^.<sent>$ ^The<det><def><sp>$ ^province<n><sg>$^'s<gen>$ ^final<adj>$ ^status<n><sg>$ ^have<vbhaver><pri><p3><sg>$ ^yet<adv>$ ^to<pr>$ ^be<vbser><inf>$ ^determine<vblex><pp>$^;<sent>$ ^talk<n><pl>$ ^on<pr>$ ^this<det><dem><sg>$ ^issue<n><sg>$ ^be<vbser><pres>$ ^schedule<vblex><pp>$ ^for<pr>$ ^later<adv>$ ^in<pr>$[ <a href='2006'>]^2006<num>$[<\/a>]^.<sent>$^.<sent>$[][<\/p>
<a name="Geography"><\/a><h2>]^Geography<n><sg>$^.<sent>$[][<\/h2><p><a href='image:UTkosovo rel small 92.jpg|thumb|left|275px|Physical map of Kosovo'>]^image<n><sg>$^:<sent>$^*UTkosovo$ ^*rel$ ^small<adj><sint>$ ^92<num>$^.<sent>$^*jpg$|^thumb<n><sg>$|^leave<vblex><past>$|^275<num>$^*px$|^Physical<adj>$ ^map<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$^.<sent>$[][<\/a><\/p>
<p>]^With<pr>$ ^a<det><ind><sg>$ ^area<n><sg>$ ^of<pr>$[ <a href='1 E10 mÂ²|10,887'>]^1<num>$ ^*E$^10<num>$ ^*mÂ$²|^10,887<num>$[<\/a> <a href='square kilometre|kmÂ²'>]^square<adj>$ ^kilometre<n><sg>$|^*kmÂ$²[<\/a> ]^(<lpar>$^4,203<num>$[ <a href='square mile|miÂ²'>]^square<adj>$ ^mile<n><sg>$|^*miÂ$²[<\/a>]^)<rpar>$ ^and<cnjcoo>$ ^a<det><ind><sg>$ ^population<n><sg>$ ^of<pr>$ ^over<pr>$ ^two<num><sp>$ ^million<num><sp>$ ^on<pr>$ ^the<det><def><sp>$ ^*eve$ ^of<pr>$ ^the<det><def><sp>$ ^1999<num>$ ^crisis<n><sg>$^,<cm>$ ^Kosovo<np><loc><sg>$ ^border<n><pl>$[ <a href='Montenegro'>]^Montenegro<np><loc><sg>$[<\/a> ]^to<pr>$ ^the<det><def><sp>$ ^northwest<n><sg>$^,<cm>$ ^with<pr>$ ^the<det><def><sp>$ ^district<n><pl>$ ^of<pr>$[ <a href='RaÅ¡ka'>]^*Ra$Å^¡<lquest>$^*ka$[<\/a>]^,<cm>$[ <a href='Toplica District|Toplica'>]^*Toplica$ ^District<n><sg>$|^*Toplica$[<\/a>]^,<cm>$[ <a href='Jablanica'>]^*Jablanica$[<\/a> ]^and<cnjcoo>$[ <a href='PÄinja District|PÄinja'>]^*PÄ$^*inja$ ^District<n><sg>$|^*PÄ$^*inja$[<\/a> ]^in<pr>$[ <a href='Central Serbia'>]^Central<adj>$ ^*Serbia$[<\/a> ]^to<pr>$ ^the<det><def><sp>$ ^North<adj><sint>$ ^and<cnjcoo>$ ^East<n><sg>$^;<sent>$[ <a href='Republic of Macedonia|Macedonia'>]^Republic<n><sg>$ ^of<pr>$ ^Macedonia<np><ant><f><sg>$|^Macedonia<np><ant><f><sg>$[<\/a> ]^to<pr>$ ^the<det><def><sp>$ ^south<adj><sint>$^,<cm>$ ^and<cnjcoo>$[ <a href='Albania'>]^*Albania$[<\/a> ]^to<pr>$ ^the<det><def><sp>$ ^southwest<n><sg>$^.<sent>$ ^The<det><def><sp>$ ^large<adj><sint><sup>$ ^city<n><pl>$ ^be<vbser><pres>$[ <a href='Prishtina'>]^*Prishtina$[<\/a>]\/[<a href='PriÅ¡tina'>]^*Pri$Å^¡<lquest>$^*tina$[<\/a> ]^the<det><def><sp>$ ^capital<n><sg>$^,<cm>$ ^with<pr>$ ^estimate<vblex><pp>$ ^500,000<num>$ ^inhabitant<n><pl>$^,<cm>$ ^and<cnjcoo>$[ <a href='Prizren'>]^*Prizren$[<\/a> ]^in<pr>$ ^the<det><def><sp>$ ^southwest<n><sg>$ ^with<pr>$ ^120,000<num>$^:<sent>$ ^five<num><sp>$ ^other<det><ind><sp>$ ^town<n><pl>$ ^have<vblex><inf>$ ^population<n><pl>$ ^in<pr>$ ^excess<n><sg>$ ^of<pr>$ ^50,000<num>$^.<sent>$^.<sent>$[][<\/p>
<a name="History"><\/a><h2>]^History<n><sg>$^.<sent>$[][<\/h2><p><em>]^See<vblex><pres>$[ <a href='History of Kosovo'>]^History<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$[<\/a>]^.<sent>$^.<sent>$[][<\/em><\/p>
<a name="Disputes_over_language,_culture_and_citizenship"><\/a><h2>]^Dispute<n><pl>$ ^over<pr>$ ^language<n><sg>$^,<cm>$ ^culture<n><sg>$ ^and<cnjcoo>$ ^citizenship<n><sg>$^.<sent>$[][<\/h2><p>]^The<det><def><sp>$ ^province<n><sg>$ ^be<vbser><pri><p3><sg>$ ^most<preadv>$ ^widely<adv>$ ^know<vblex><pp>$ ^as<pr>$ ^'<apos>$^Kosovo<np><loc><sg>$^'<apos>$ ^and<cnjcoo>$ ^this<prn><tn><mf><sg>$ ^have<vbhaver><pri><p3><sg>$ ^become<vblex><pp>$ ^the<det><def><sp>$ ^standard<n><sg>$ ^in<pr>$ ^international<adj>$ ^and<cnjcoo>$ ^Unite<vblex><pp>$ ^Nation<n><pl>$ ^usage<n><sg>$^.<sent>$ ^In<pr>$[ <a href='Albanian language|Albanian'>]^Albanian<adj>$ ^language<n><sg>$|^Albanian<n><sg>$[<\/a> ]^this<det><dem><sg>$ ^name<n><sg>$ ^become<vblex><pri><p3><sg>$ ^'<apos>$^*Kosova$^'<apos>$^,<cm>$ ^which<prn><itg><m><sp>$ ^be<vbser><pri><p3><sg>$ ^more<preadv>$ ^often<adv>$ ^find<vblex><pp>$ ^within<pr>$ ^Kosovo<np><loc><sg>$ ^and<cnjcoo>$ ^in<pr>$ ^official<adj>$ ^use<n><sg>$ ^by<pr>$ ^the<det><def><sp>$ ^Provisional<adj>$ ^Institution<n><pl>$^,<cm>$ ^though<cnjadv>$ ^both<det><ind><pl>$ ^Albanian<adj>$ ^and<cnjcoo>$ ^*Serbian$ ^be<vbser><pres>$ ^official<adj>$ ^language<n><pl>$^.<sent>$ ^*Wherever$ ^political<adj>$ ^and<cnjcoo>$ ^cultural<adj>$ ^sensitivity<n><sg>$ ^be<vbser><pres>$ ^particularly<adv>$ ^important<adj>$^,<cm>$ ^the<det><def><sp>$ ^international<adj>$ ^community<n><sg>$ ^will<vaux><inf>$ ^use<vblex><inf>$ ^'<apos>$^Kosovo<np><loc><sg>$\/^*Kosova$^'<apos>$ ^to<pr>$ ^describe<vblex><inf>$ ^the<det><def><sp>$ ^province<n><sg>$ ^and<cnjcoo>$ ^adopt<vblex><inf>$ ^a<det><ind><sg>$ ^similar<adj>$ ^standard<n><sg>$ ^for<pr>$ ^many<det><qnt><pl>$ ^place<n><sg>$ ^name<n><pl>$^.<sent>$ ^*Whilst$ ^the<det><def><sp>$ ^formal<adj>$ ^title<n><sg>$ ^'<apos>$^Republic<n><sg>$ ^of<pr>$ ^*Kosova$^'<apos>$ ^have<vblex><pri><p3><sg>$ ^fall<vblex><pp>$ ^out of<pr>$ ^use<n><sg>$ ^with<pr>$ ^the<det><def><sp>$ ^integration<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$ ^Albanian<adj>$ ^politics<n><sg>$ ^into<pr>$ ^the<det><def><sp>$ ^*UNMIK$ ^system<n><sg>$^,<cm>$ ^the<det><def><sp>$ ^formal<adj>$ ^*Serbian$ ^title<n><sg>$ ^'<apos>$^Kosovo<np><loc><sg>$ ^*i$ ^*Metohija$^'<apos>$ ^remains<n><pl>$ ^in<pr>$ ^colloquial<adj>$ ^and<cnjcoo>$ ^official<adj>$ ^use<n><sg>$ ^in<pr>$ ^part<n><pl>$ ^of<pr>$ ^Kosovo<np><loc><sg>$ ^and<cnjcoo>$ ^in<pr>$ ^*Serbia$ ^proper<adj>$^,<cm>$ ^where<rel><adv>$ ^parallel<adj>$ ^institution<n><pl>$ ^for<pr>$ ^Kosovo<np><loc><sg>$ ^remain<vblex><pres>$ ^until<pr>$ ^final<adj>$ ^status<n><sg>$ ^be<vbser><pri><p3><sg>$ ^resolve<vblex><pp>$^.<sent>$^.<sent>$[][<\/p>
<p>]^The<det><def><sp>$ ^question<n><sg>$ ^of<pr>$ ^what<prn><itg><m><sp>$ ^to<pr>$ ^call<vblex><inf>$ ^the<det><def><sp>$ ^inhabitant<n><pl>$ ^of<pr>$ ^Kosovo<np><loc><sg>$ ^*collectively$ ^have<vbhaver><pri><p3><sg>$ ^also<adv>$ ^arouse<vblex><pp>$ ^some<det><qnt><sp>$ ^debate<n><sg>$^.<sent>$ ^The<det><def><sp>$ ^two<num><sp>$ ^word<n><pl>$ ^accept<vblex><pp>$ ^by<pr>$[ <a href='Oxford English Dictionary'>]^the<det><def><sp>$ ^*Oxford$ ^English<adj>$ ^Dictionary<n><sg>$[<\/a> ]^be<vbser><pres>$ "^*Kosovar$" ^(<lpar>$^*borrowed$ ^from<pr>$ ^Albanian<n><sg>$^)<rpar>$^,<cm>$ ^the most<det><qnt><sp>$ ^widely<adv>$ ^use<vblex><pp>$ ^*variant$ ^in<pr>$ ^English<adj>$^,<cm>$ ^by<pr>$ ^a<det><ind><sg>$ ^long<adj><sint>$ ^way<n><sg>$^,<cm>$ ^and<cnjcoo>$ "^*Kosovan$" ^(<lpar>$^use<vblex><ger>$ ^the<det><def><sp>$ ^English<adj>$ ^rule<n><pl>$ ^for<pr>$[ <a href='demonym'>]^*demonyms$[<\/a>]^)<rpar>$ ^much less<adv>$ ^use<vblex><pp>$^.<sent>$ ^As<cnjadv>$ ^Kosovo<np><loc><sg>$ ^have<vblex><pri><p3><sg>$ ^no<adv>$ ^formal<adj>$ ^*statehood$^,<cm>$ ^current<adj>$ ^international<adj>$ ^usage<n><sg>$ ^be<vbser><pri><p3><sg>$ ^to<pr>$ ^refer<vblex><inf>$ ^to<pr>$ ^Kosovo<np><loc><sg>$[ <a href='Serbs'>]^*Serbs$[<\/a> ]^and<cnjcoo>$ ^Kosovo<np><loc><sg>$[ <a href='Albanians'>]^Albanian<n><pl>$[<\/a>]^.<sent>$ ^Most of<det><qnt><sp>$ ^the<det><def><sp>$ ^Albanian<adj>$^-<guio>$^descend<vblex><pp>$ ^community<n><sg>$ ^in<pr>$ ^Kosovo<np><loc><sg>$ ^would<vaux><inf>$ ^prefer<vblex><inf>$ ^the<det><def><sp>$ ^use<n><sg>$ ^of<pr>$ ^*Kosovar$ ^or<cnjcoo>$ ^*Kosovan$ ^because of<pr>$ ^the<det><def><sp>$ ^attendant<n><sg>$ ^political<adj>$ ^*overtones$^,<cm>$ ^*whilst$ ^the<det><def><sp>$ ^*Serb$ ^minority<n><sg>$ ^continue<vblex><pres>$ ^to<pr>$ ^think<vblex><inf>$ ^of<pr>$ ^themselves<prn><ref><p3><mf><pl>$ ^as<pr>$ ^*Serb$ ^or<cnjcoo>$ ^*Serbian$ ^(<lpar>$^from<pr>$ ^Kosovo<np><loc><sg>$^)<rpar>$^.<sent>$^.<sent>$[][<\/p>
<p>]^As for<pr>$ ^language<n><sg>$ ^and<cnjcoo>$ ^citizenship<n><sg>$^,<cm>$ ^so<preadv>$ ^for<pr>$ ^cultural<adj>$ ^and<cnjcoo>$ ^political<adj>$ ^symbol<n><pl>$^.<sent>$ ^The<det><def><sp>$ ^province<n><sg>$ ^have<vbhaver><pri><p3><sg>$ ^never<adv>$ ^have<vblex><past>$ ^a<det><ind><sg>$ ^official<adj>$ ^flag<n><sg>$ ^of<pr>$ ^its<det><pos><sp>$ ^own<adj>$^.<sent>$ ^The<det><def><sp>$[ <a href='Flag of Albania|Albanian flag'>]^Flag<n><sg>$ ^of<pr>$ ^*Albania$|^Albanian<adj>$ ^flag<n><sg>$[<\/a> ]^be<vbser><pri><p3><sg>$ ^use<vblex><pp>$ ^*unofficially$ ^by<pr>$ ^the<det><def><sp>$ ^Kosovo<np><loc><sg>$ ^Albanian<adj>$^-<guio>$^dominate<vblex><pp>$ ^administration<n><sg>$ ^and<cnjcoo>$ ^the<det><def><sp>$ ^vast<adj><sint>$ ^majority<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$ ^Albanian<n><pl>$^;<sent>$ ^although<cnjadv>$ ^recently<adv>$ ^the<det><def><sp>$ ^presidential<adj>$ ^flag<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^presidency<n><sg>$ ^be<vbser><pri><p3><sg>$ ^be<vbser><ger>$ ^use<vblex><pp>$ ^as<pr>$ ^a<det><ind><sg>$ ^unofficial<adj>$ ^flag<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$^,<cm>$ ^as<cnjadv>$ ^can<vaux><past>$ ^be<vbser><inf>$ ^see<vblex><pp>$ ^during<pr>$[ <a href='Ibrahim Rugova'>]^Ibrahim<np><ant><m><sg>$ ^*Rugova$[<\/a>]^'s<gen>$ ^funeral<n><pl>$[ <a href='http:\/\/sq.wikipedia.org\/wiki\/Ibrahim_Rugova'>]^1<num>$[<\/a> ]^.<sent>$^.<sent>$[][<\/p>
<p>]^The<det><def><sp>$ ^*Serb$^-<guio>$^*inhabited$ ^area<n><sg>$ ^of<pr>$ ^north<adj><sint>$ ^Kosovo<np><loc><sg>$ ^use<vblex><pri><p3><sg>$ ^only<adv>$ ^the<det><def><sp>$[ <a href='flag of Serbia'>]^flag<n><sg>$ ^of<pr>$ ^*Serbia$[<\/a>]^,<cm>$ ^which<prn><itg><m><sp>$ ^be<vbser><pri><p3><sg>$ ^formally<adv>$ ^the<det><def><sp>$ ^flag<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^whole<n><sg>$ ^of<pr>$ ^*Serbia$ ^include<vblex><ger>$ ^Kosovo<np><loc><sg>$^,<cm>$ ^although<cnjadv>$ ^this<det><dem><sg>$ ^usage<n><sg>$ ^be<vbser><pri><p3><sg>$ ^reject<vblex><pp>$ ^by<pr>$ ^virtually<adv>$ ^all<prn><tn><mf><sp>$ ^Kosovo<np><loc><sg>$ ^Albanian<n><pl>$^.<sent>$^.<sent>$[][<\/p>
<a name="Politics_and_international_status"><\/a><h2>]^Politics<n><sg>$ ^and<cnjcoo>$ ^international<adj>$ ^status<n><sg>$^.<sent>$[][<\/h2><p>]{{^Politics<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$}}[
]^Kosovo<np><loc><sg>$^'s<gen>$ ^international<adj>$ ^status<n><sg>$ ^be<vbser><pri><p3><sg>$ ^anomalous<adj>$ ^in<adv>$ ^that<cnjsub>$ ^although<cnjadv>$ ^prpers<prn><subj><p3><nt><sg>$ ^be<vbser><pri><p3><sg>$ ^a<det><ind><sg>$ ^*Serbian$ ^province<n><sg>$ ^within<pr>$ ^the<det><def><sp>$ ^State<adj>$ ^Union<n><sg>$ ^of<pr>$ ^*Serbia$ ^and<cnjcoo>$ ^Montenegro<np><loc><sg>$^,<cm>$ ^administration<n><sg>$ ^be<vbser><pri><p3><sg>$ ^*presently$ ^conduct<vblex><pp>$ ^by<pr>$[ <a href='United Nations'>]^the<det><def><sp>$ ^Unite<vblex><pp>$ ^Nation<n><pl>$[<\/a> ]^with<pr>$ ^little<det><qnt><sg>$ ^or<cnjcoo>$ ^no<det><ind><sg>$ ^involvement<n><sg>$ ^on<pr>$ ^the<det><def><sp>$ ^part<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^*Serbia$[  ]^government<n><sg>$ ^(<lpar>$^under<pr>$ ^Security<n><sg>$ ^Council<n><sg>$ ^resolution<n><sg>$ ^1244<num>$ ^of<pr>$[ <a href='10 June'>]^10<num>$ ^June<n><sg>$[<\/a> <a href='1999'>]^1999<num>$[<\/a>]^;<sent>$ ^see<vblex><pres>$[ <a href='http:\/\/www.un.org\/Docs\/scres\/1999\/sc99.htm Security Council Resolutions 1999'>]^2<num>$[<\/a>]^)<rpar>$^.<sent>$[  ]^The<det><def><sp>$ ^government<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^province<n><sg>$ ^be<vbser><pri><p3><sg>$ ^the<det><def><sp>$ ^responsibility<n><sg>$ ^of<pr>$ ^the<det><def><sp>$[ <a href='United Nations Mission in Kosovo'>]^Unite<vblex><pp>$ ^Nation<n><pl>$ ^Mission<n><sg>$ ^in<pr>$ ^Kosovo<np><loc><sg>$[<\/a> ]^(<lpar>$^*UNMIK$^)<rpar>$^.<sent>$ ^Under<pr>$ ^the<det><def><sp>$ ^term<n><pl>$ ^of<pr>$ ^the<det><def><sp>$[ <a href='Kumanovo agreement'>]^*Kumanovo$ ^agreement<n><sg>$[<\/a> ]^and<cnjcoo>$ ^subsequent<adj>$ ^UN<n><acr><sg>$[ <a href='Security Council'>]^Security<n><sg>$ ^Council<n><sg>$[<\/a> <a href='Resolution 1244'>]^Resolution<n><sg>$ ^1244<num>$[<\/a>]^,<cm>$ ^which<prn><itg><m><sp>$ ^end<vblex><past>$ ^the<det><def><sp>$[ <a href='Kosovo War'>]^Kosovo<np><loc><sg>$ ^War<n><sg>$[<\/a>]^,<cm>$ ^security<n><sg>$ ^be<vbser><pri><p3><sg>$ ^provide<vblex><pp>$ ^by<pr>$ ^the<det><def><sp>$ ^Kosovo<np><loc><sg>$ ^Force<n><sg>$ ^(<lpar>$^*KFOR$^)<rpar>$^,<cm>$ ^which<prn><itg><m><sp>$ ^be<vbser><pri><p3><sg>$ ^lead<vblex><pp>$ ^by<pr>$[ <a href='NATO'>]^NATO<n><acr><sg>$[<\/a> ]^and<cnjcoo>$ ^be<vbser><pri><p3><sg>$ ^*answerable$ ^to<pr>$ ^*UNMIK$^.<sent>$^.<sent>$[][<\/p>
<p>]^*UNMIK$ ^have<vblex><pri><p3><sg>$ ^so<preadv>$ ^far<adv>$ ^establish<vblex><pp>$ ^a<det><ind><sg>$ ^provisional<adj>$ ^assembly<n><sg>$^,<cm>$ ^provisional<adj>$ ^government<n><sg>$ ^and<cnjcoo>$ ^the<det><def><sp>$ ^office<n><sg>$ ^of<pr>$ ^provisional<adj>$ ^president<n><sg>$^,<cm>$ ^which<prn><itg><m><sp>$ ^be<vbser><pres>$ ^legislative<adj>$ ^and<cnjcoo>$ ^executive<adj>$ ^body<n><pl>$ ^under<pr>$ ^*UNMIK$^'s<gen>$ ^control<n><sg>$^.<sent>$ ^Control<n><sg>$ ^of<pr>$ ^security<n><sg>$^,<cm>$ ^justice<n><sg>$ ^and<cnjcoo>$ ^external<adj>$ ^affair<n><pl>$ ^be<vbser><pres>$ ^still<adv>$ ^under<pr>$ ^full<adj><sint>$ ^*UNMIK$ ^control<n><sg>$^.<sent>$ ^Election<n><pl>$ ^for<pr>$[ <a href='Assembly of Kosovo'>]^the<det><def><sp>$ ^Assembly<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$[<\/a> ]^be<vbser><past>$ ^hold<vblex><pp>$ ^in<pr>$ ^November<n><sg>$[ <a href='2001'>]^2001<num>$[<\/a> ]^and<cnjcoo>$ ^again<adv>$ ^in<pr>$[ <a href='2004'>]^2004<num>$[<\/a>]^.<sent>$[ <a href='Ibrahim Rugova'>]^Ibrahim<np><ant><m><sg>$ ^*Rugova$[<\/a> ]^be<vbser><past><p3><sg>$ ^elect<vblex><pp>$ ^as<pr>$ ^president<n><sg>$ ^in<pr>$ ^March<n><sg>$[ <a href='2002'>]^2002<num>$[<\/a>]^.<sent>$ ^The<det><def><sp>$ ^seat<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^assembly<n><sg>$^,<cm>$ ^government<n><sg>$ ^and<cnjcoo>$ ^president<n><sg>$ ^be<vbser><pri><p3><sg>$ ^in<pr>$[ <a href='Prishtina'>]^*Prishtina$[<\/a>]\/[<a href='Pristina'>]^*Pristina$[<\/a>]^.<sent>$ ^So<preadv>$ ^far<adv>$^,<cm>$ ^the<det><def><sp>$ ^parliament<n><sg>$ ^have<vbhaver><pri><p3><sg>$ ^*enacted$ ^and<cnjcoo>$ ^*UNMIK$ ^approve<vblex><past>$ ^a<det><ind><sg>$ ^constitutional<adj>$ ^framework<n><sg>$^,<cm>$ ^customs<n><pl>$ ^code<n><sg>$^,<cm>$ ^and<cnjcoo>$ ^two<num><sp>$ ^*criminal$ ^code<n><pl>$^.<sent>$^.<sent>$[][<\/p>
<p>]^The<det><def><sp>$ ^Constitutional<adj>$ ^Framework<n><sg>$ ^*enacted$ ^by<pr>$ ^the<det><def><sp>$ ^Kosovo<np><loc><sg>$ ^assembly<n><sg>$ ^(<lpar>$^with<pr>$ ^UN<n><acr><sg>$ ^Security<n><sg>$ ^Council<n><sg>$ ^approval<n><sg>$^)<rpar>$ ^have<vbhaver><pri><p3><sg>$ ^adopt<vblex><pp>$ ^a<det><ind><sg>$ ^policy<n><sg>$ ^of<pr>$[ <a href='affirmative action'>]^affirmative<adj>$ ^action<n><sg>$[<\/a> ]^in<pr>$ ^the<det><def><sp>$ ^assembly<n><sg>$ ^to<pr>$ ^ensure<vblex><inf>$ ^that<cnjsub>$ ^the<det><def><sp>$ ^province<n><sg>$^'s<gen>$ ^minority<n><pl>$ ^be<vbser><pres>$ ^properly<adv>$ ^represent<vblex><pp>$^.<sent>$ ^Out of<pr>$ ^120<num>$ ^seat<n><pl>$^,<cm>$ ^10<num>$ ^be<vbser><pres>$ ^reserve<vblex><pp>$ ^for<pr>$ ^*Serbs$ ^and<cnjcoo>$ ^another<prn><tn><m><sg>$ ^10<num>$ ^for<cnjadv>$ ^non<adv>$^-<guio>$^Albanian<adj>$ ^minority<n><pl>$^,<cm>$ ^while<cnjadv>$ ^the<det><def><sp>$ ^remain<vblex><ger>$ ^100<num>$ ^seat<n><pl>$ ^be<vbser><pres>$ ^elect<vblex><pp>$ ^through<pr>$ ^direct<adj>$ ^vote<vblex><ger>$^.<sent>$ ^*UNIK$ ^do<vbdo><pri><p3><sg>$ ^not<adv>$ ^take<vblex><inf>$ ^account<n><sg>$^,<cm>$ ^though<adv>$^,<cm>$ ^of<pr>$ ^*Serbs$ ^and<cnjcoo>$ ^other<det><ind><sp>$ ^non<adv>$^-<guio>$^Albanian<n><pl>$ ^who<rel><an><mf><sp>$ ^have<vbhaver><inf>$ ^leave<vblex><pp>$ ^Kosovo<np><loc><sg>$ ^as a result of<pr>$ ^*interethnic$ ^tension<n><sg>$^,<cm>$ ^many<prn><tn><mf><pl>$ ^of<pr>$ ^whom<rel><an><mf><sp>$ ^be<vbser><pres>$ ^unable<adj>$ ^to<pr>$ ^*reclaim$ ^lose<vblex><pp>$ ^property<n><sg>$ ^or<cnjcoo>$ ^safely<adv>$ ^to<pr>$ ^attend<vblex><inf>$ ^election<n><pl>$^.<sent>$ ^The<det><def><sp>$ ^process<n><sg>$ ^of<pr>$ ^'<apos>$^return<n><pl>$^'<apos>$ ^of<pr>$ ^this<det><dem><pl>$ ^displace<vblex><pp>$ ^person<n><pl>$ ^have<vbhaver><pri><p3><sg>$ ^yet<adv>$ ^to<pr>$ ^begin<vblex><inf>$ ^in earnest<adv>$^,<cm>$ ^as a result of<pr>$ ^insufficient<adj>$ ^funding<n><sg>$ ^and<cnjcoo>$ ^a<det><ind><sg>$ ^perceive<vblex><pp>$ ^inability<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^UN<n><acr><sg>$ ^to<pr>$ ^control<vblex><inf>$ ^violence<n><sg>$ ^against<pr>$ ^minority<n><sg>$ ^group<n><pl>$^,<cm>$ ^as well<adv>$ ^as a<pr>$ ^concern<n><sg>$ ^on<pr>$ ^the<det><def><sp>$ ^part<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$ ^Albanian<n><pl>$ ^that<cnjsub>$ ^a<det><ind><sg>$ ^increase<vblex><pp>$ ^proportion<n><sg>$ ^of<pr>$ ^*Serbs$ ^will<vaux><inf>$ ^undermine<vblex><inf>$ ^the<det><def><sp>$ ^chance<n><pl>$ ^for<pr>$ ^a<det><ind><sg>$ ^independent<adj>$ ^Kosovo<np><loc><sg>$^.<sent>$^.<sent>$[][<\/p>
<p>]^Kosovo<np><loc><sg>$ ^be<vbser><pri><p3><sg>$ ^still<adv>$ ^*recognised$ ^*internationally$ ^as a<pr>$ ^part<n><sg>$ ^of<pr>$ ^*Serbia$^.<sent>$ ^Its<det><pos><sp>$ ^final<adj>$ ^status<n><sg>$ ^have<vbhaver><pri><p3><sg>$ ^not<adv>$ ^yet<adv>$ ^be<vbser><pp>$ ^resolve<vblex><pp>$^,<cm>$ ^though<cnjadv>$ ^talk<n><pl>$ ^on<pr>$ ^the<det><def><sp>$ ^subject<n><sg>$ ^be<vbser><pres>$ ^plan<vblex><pp>$ ^for<pr>$ ^2006<num>$^,<cm>$ ^and<cnjcoo>$ ^considerable<adj>$ ^difficulty<n><pl>$ ^lie<n><sg>$ ^ahead<adv>$ ^in<pr>$ ^*reconciling$ ^the<det><def><sp>$ ^*irreconcilable$ ^Kosovo<np><loc><sg>$ ^Albanian<n><sg>$^,<cm>$ ^Kosovo<np><loc><sg>$ ^*Serb$ ^and<cnjcoo>$ ^Belgrade<np><loc><sg>$ ^position<n><pl>$^.<sent>$ ^The<det><def><sp>$ ^Kosovo<np><loc><sg>$ ^Albanian<n><pl>$ ^reject<vblex><inf>$ ^*Serbian$ ^sovereignty<n><sg>$ ^and<cnjcoo>$ ^demand<n><sg>$ ^secession<n><sg>$ ^from<pr>$ ^the<det><def><sp>$ ^country<n><sg>$^.<sent>$ ^On the other side<adv>$^,<cm>$ ^*Serbia$ ^be<vbser><pri><p3><sg>$ ^*opposed$ ^to<pr>$ ^yielding<adj>$ ^any<prn><tn><mf><sp>$ ^of<pr>$ ^its<det><pos><sp>$ ^territory<n><sg>$ ^and<cnjcoo>$ ^domestic<adj>$ ^opinion<n><sg>$^,<cm>$ ^support<vblex><pp>$ ^by<pr>$ ^the<det><def><sp>$ ^existence<n><sg>$ ^of<pr>$ ^a<det><ind><sg>$ ^century<n><pl>$ ^old<adj><sint>$ ^write<vblex><pp>$^,<cm>$ ^material<n><sg>$ ^and<cnjcoo>$ ^architectural<adj>$ ^history<n><sg>$^,<cm>$ ^continue<vblex><pri><p3><sg>$ ^to<pr>$ ^see<vblex><inf>$ ^the<det><def><sp>$ ^province<n><sg>$ ^as<pr>$ ^the<det><def><sp>$ ^*heartland$ ^of<pr>$ ^*Serbian$ ^culture<n><sg>$^.<sent>$^.<sent>$[][<\/p>
<p>]^The<det><def><sp>$ ^international<adj>$ ^community<n><sg>$ ^be<vbser><pri><p3><sg>$ ^reluctant<adj>$ ^to<pr>$ ^see<vblex><inf>$ ^Kosovo<np><loc><sg>$ ^become<vblex><pres>$ ^independent<adj>$^,<cm>$ ^as<cnjadv>$ ^its<det><pos><sp>$ ^independence<n><sg>$ ^without<pr>$ ^Belgrade<np><loc><sg>$^'s<gen>$ ^consent<n><sg>$ ^would<vaux><inf>$ ^*violate$[ <a href='international law'>]^international<adj>$ ^law<n><sg>$[<\/a> ]^(<lpar>$^the<det><def><sp>$ ^principle<n><pl>$ ^of<pr>$[ <a href='territorial integrity'>]^territorial<adj>$ ^integrity<n><sg>$[<\/a> ]^and<cnjcoo>$[ <a href='noninterference in internal affairs'>]^*noninterference$ ^in<pr>$ ^internal<adj>$ ^affair<n><pl>$[<\/a>]^)<rpar>$^.<sent>$ ^Prpers<prn><subj><p3><nt><sg>$ ^can<vaux><past>$ ^also<adv>$ ^potentially<adv>$ ^provide<vblex><inf>$ ^a<det><ind><sg>$ ^precedent<n><sg>$ ^for<pr>$ ^the<det><def><sp>$ ^parallel<adj>$ ^*Serb$ ^demand<n><pl>$ ^of<pr>$ ^secession<n><sg>$ ^for<pr>$[ <a href='Republika Srpska'>]^the<det><def><sp>$ ^*Republika$ ^*Srpska$[<\/a> ]^from<pr>$[ <a href='Bosnia and Herzegovina'>]^Bosnia<np><loc><sg>$ ^and<cnjcoo>$ ^*Herzegovina$[<\/a>]^,<cm>$ ^*re$^-<guio>$^*igniting$ ^tension<n><sg>$ ^in<pr>$ ^that<det><dem><sg>$ ^country<n><sg>$^.<sent>$ ^The<det><def><sp>$[ <a href='NATO'>]^NATO<n><acr><sg>$[<\/a> ]^country<n><pl>$ ^insist<vblex><pp>$ ^on<pr>$ ^the<det><def><sp>$ ^republican<adj>$ ^border<n><pl>$ ^as<pr>$ ^the<det><def><sp>$ ^only<adj>$ ^acceptable<adj>$ ^solution<n><sg>$ ^during<pr>$ ^the<det><def><sp>$ ^war<n><pl>$ ^in<pr>$[ <a href='Croatia'>]^Croatia<np><loc><sg>$[<\/a> ]^and<cnjcoo>$[ <a href='Bosnia-Herzegovina'>]^Bosnia<np><loc><sg>$^-<guio>$^*Herzegovina$[<\/a> ]^in<pr>$ ^the<det><def><sp>$ ^1990<num>$^*s$^,<cm>$ ^but<cnjcoo>$ ^this<prn><tn><mf><sg>$ ^do<vbdo><pri><p3><sg>$ ^not<adv>$ ^rule<vblex><inf>$ ^out<pr>$ ^that<rel><an><mf><sp>$ ^prpers<prn><subj><p3><mf><pl>$ ^might<vaux><inf>$ ^*revisit$ ^this<prn><tn><mf><sg>$ ^in<pr>$ ^the<det><def><sp>$ ^case<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$ ^*vis$^-<guio>$Ã ^-<guio>$^*vis$ ^*Serbia$ ^and<cnjcoo>$ ^Montenegro<np><loc><sg>$^.<sent>$ ^Question<n><pl>$ ^have<vbhaver><inf>$ ^also<adv>$ ^be<vbser><pp>$ ^raise<vblex><pp>$ ^about<pr>$ ^whether<cnjadv>$ ^a<det><ind><sg>$ ^independent<adj>$ ^Kosovo<np><loc><sg>$ ^would<vaux><inf>$ ^be<vbser><inf>$ ^politically<adv>$ ^or<cnjcoo>$ ^economically<adv>$ ^viable<adj>$^,<cm>$ ^give<vblex><pp>$ ^its<det><pos><sp>$ ^small<adj><sint>$ ^size<n><sg>$^,<cm>$ ^the<det><def><sp>$ ^state<n><sg>$ ^of<pr>$ ^its<det><pos><sp>$ ^economy<n><sg>$ ^and<cnjcoo>$ ^fear<vblex><pri><p3><sg>$ ^that<cnjsub>$ ^*criminal$ ^and<cnjcoo>$ ^smuggling<n><sg>$ ^network<n><pl>$ ^have<vblex><pres>$ ^strong<adj><sint>$ ^position<n><pl>$ ^there<adv>$^.<sent>$^.<sent>$[][<\/p>
<p>]^*UNMIK$ ^be<vbser><pri><p3><sg>$ ^issue<vblex><ger>$ ^travel<n><sg>$ ^document<n><pl>$ ^which<rel><an><mf><sp>$ ^serve<vblex><inf>$ ^instead of<pr>$[ <a href='passport'>]^passport<n><pl>$[<\/a> ]^in<pr>$ ^country<n><pl>$ ^which<rel><an><mf><sp>$ ^*recognise$ ^prpers<prn><obj><p3><mf><pl>$^,<cm>$ ^and<cnjcoo>$ ^issue<n><pl>$ ^identity<n><sg>$ ^card<n><pl>$ ^and<cnjcoo>$ ^car<n><sg>$ ^plate<n><pl>$^,<cm>$ ^which<prn><itg><m><sp>$ ^again<adv>$ ^be<vbser><pres>$ ^valid<adj>$ ^only<adv>$ ^in<pr>$ ^certain<adj>$ ^country<n><pl>$^.<sent>$ ^*UNMIK$ ^have<vbhaver><pri><p3><sg>$ ^create<vblex><pp>$ ^a<det><ind><sg>$ ^police<adj>$ ^force<n><sg>$ ^(<lpar>$^the<det><def><sp>$[ <a href='Kosovo Police Service'>]^Kosovo<np><loc><sg>$ ^Police<adj>$ ^Service<n><sg>$[<\/a>]^)<rpar>$ ^with<pr>$ ^employee<n><pl>$ ^from<pr>$ ^all<predet><sp>$ ^ethnic<adj>$ ^community<n><pl>$ ^(<lpar>$^Albanian<n><sg>$^,<cm>$ ^*Serbian$^,<cm>$ ^*Roma$^,<cm>$ ^*Bosniac$^,<cm>$ ^*etc$^)<rpar>$ ^and<cnjcoo>$ ^manage<vblex><pri><p3><sg>$ ^the<det><def><sp>$ ^province<n><sg>$^'s<gen>$ ^railway<n><pl>$ ^and<cnjcoo>$ ^*airline$ ^(<lpar>$[<a href='Kosova Airlines'>]^*Kosova$ ^*Airlines$[<\/a>]^)<rpar>$^.<sent>$ ^The<det><def><sp>$ ^*airspace$ ^of<pr>$ ^the<det><def><sp>$ ^province<n><sg>$ ^be<vbser><pri><p3><sg>$ ^control<vblex><pp>$ ^by<pr>$ ^*KFOR$^.<sent>$^.<sent>$[][<\/p>
<p>]^On<pr>$[ <a href='January 21'>]^January<n><sg>$ ^21<num>$[<\/a>]^,<cm>$[ <a href='2006'>]^2006<num>$[<\/a>]^,<cm>$ ^the<det><def><sp>$ ^President<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$^,<cm>$ ^Dr<n><sg>$[<a href='Ibrahim Rugova'>]^Ibrahim<np><ant><m><sg>$ ^*Rugova$[<\/a>]^,<cm>$ ^die<vblex><past>$ ^age<vblex><pp>$ ^61<num>$^.<sent>$^.<sent>$[][<\/p>
<a name="Economy"><\/a><h2>]^Economy<n><sg>$^.<sent>$[][<\/h2><p><a href='UNMIK'>]^*UNMIK$[<\/a> ]^declare<vblex><past>$ ^the<det><def><sp>$[ <a href='euro'>]^euro<n><sg>$[<\/a> ]^to<pr>$ ^be<vbser><inf>$ ^official<adj>$ ^currency<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^province<n><sg>$ ^in<pr>$[ <a href='2001'>]^2001<num>$[<\/a> ]^in<pr>$ ^the<det><def><sp>$ ^course<n><sg>$ ^of<pr>$ ^implement<vblex><ger>$ ^a<det><ind><sg>$ ^currency<n><sg>$ ^reform<n><sg>$^.<sent>$ ^This<prn><tn><mf><sg>$ ^be<vbser><past><p3><sg>$ ^undertake<vblex><pp>$ ^to<pr>$ ^replace<vblex><inf>$ ^the<det><def><sp>$ ^previous<adj>$ ^*widespread$ ^use<n><sg>$ ^of<pr>$ ^the<det><def><sp>$[ <a href='Deutschmark'>]^*Deutschmark$[<\/a>]^,<cm>$ ^which<prn><itg><m><sp>$ ^have<vbhaver><past>$ ^become<vblex><pp>$[ <em>]^*de$[<\/em> ]^*facto$ ^currency<n><sg>$ ^even<adv>$ ^before<pr>$ ^the<det><def><sp>$ ^1999<num>$ ^war<n><sg>$^.<sent>$ ^However<adv>$^,<cm>$ ^the<det><def><sp>$[ <a href='Serbian dinar'>]^*Serbian$ ^*dinar$[<\/a> ]^remain<vblex><pri><p3><sg>$ ^a<det><ind><sg>$ ^official<adj>$ ^currency<n><sg>$^,<cm>$ ^though<adv>$ ^use<vblex><pp>$ ^principally<adv>$ ^in<pr>$[ <a href='Kosovo Serb enclaves'>]^the<det><def><sp>$ ^Kosovo<np><loc><sg>$ ^*Serb$ ^*enclaves$[<\/a>]^;<sent>$ ^prpers<prn><subj><p3><nt><sg>$ ^be<vbser><pri><p3><sg>$ ^only<adv>$ ^use<vblex><pp>$ ^*sporadically$ ^outside<pr>$ ^of<pr>$ ^prpers<prn><obj><p3><mf><pl>$^.<sent>$ ^Most<det><qnt><sp>$ ^trade<n><sg>$ ^be<vbser><pri><p3><sg>$ ^conduct<vblex><pp>$ ^use<vblex><ger>$ ^the<det><def><sp>$ ^euro<n><sg>$^,<cm>$ ^Kosovo<np><loc><sg>$^'s<gen>$ ^administration<n><sg>$ ^use<n><pl>$ ^euro<n><sg>$ ^exclusively<adv>$^,<cm>$ ^and<cnjcoo>$ ^all<predet><sp>$ ^commercial<adj>$ ^bank<n><pl>$ ^use<vblex><inf>$ ^the<det><def><sp>$ ^euro<n><sg>$ ^as<pr>$ ^the<det><def><sp>$ ^primary<adj>$ ^currency<n><sg>$^.<sent>$ ^Of<pr>$ ^other<det><ind><sp>$ ^international<adj>$ ^currency<n><pl>$^,<cm>$ ^the<det><def><sp>$[ <a href='United States dollar'>]^United States<np><loc><sg>$ ^dollar<n><sg>$[<\/a> ]^and<cnjcoo>$[ <a href='Swiss franc'>]^Swiss<adj>$ ^*franc$[<\/a> ]^be<vbser><pres>$ ^the most<det><qnt><sp>$ ^*widespread$^.<sent>$^.<sent>$[][<\/p>
<a name="Demographics"><\/a><h2>]^*Demographics$^.<sent>$[][<\/h2><p>]^Ethnic<adj>$ ^Albanian<n><pl>$ ^now<adv>$ ^comprise<vblex><inf>$ ^almost<adv>$ ^90%<num><percent>$ ^of<pr>$ ^the<det><def><sp>$ ^population<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^province<n><sg>$^,<cm>$ ^a<det><ind><sg>$ ^percentage<n><sg>$ ^which<rel><an><mf><sp>$ ^have<vbhaver><pri><p3><sg>$ ^increase<vblex><pp>$ ^over<pr>$ ^time<n><sg>$ ^as a result of<pr>$ ^a<det><ind><sg>$ ^high<adj><sint>$ ^birth<n><sg>$ ^rate<n><sg>$^,<cm>$ ^illegal<adj>$ ^Albanian<adj>$ ^immigration<n><sg>$ ^and<cnjcoo>$ ^non<adv>$^-<guio>$^Albanian<adj>$ ^emigration<n><sg>$^.<sent>$ ^Though<cnjadv>$ ^mass<n><sg>$ ^emigration<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$ ^Albanian<n><pl>$ ^during<pr>$ ^the<det><def><sp>$ ^Kosovo<np><loc><sg>$ ^crisis<n><sg>$ ^be<vbser><past><p3><sg>$ ^allegedly<adv>$ ^a<det><ind><sg>$ ^decide<vblex><ger>$ ^factor<n><sg>$ ^in<pr>$ ^NATO<n><acr><sg>$ ^intervention<n><sg>$^,<cm>$ ^the<det><def><sp>$ ^Unite<vblex><pp>$ ^Nation<n><pl>$ ^have<vbhaver><pri><p3><sg>$ ^succeed<vblex><pp>$ ^in<pr>$ ^*resettling$ ^and<cnjcoo>$ ^*rehousing$ ^all<prn><tn><mf><sp>$ ^displace<vblex><pp>$ ^Kosovo<np><loc><sg>$ ^Albanian<n><pl>$^.<sent>$ ^In<pr>$ ^the<det><def><sp>$ ^*aftermath$ ^of<pr>$ ^the<det><def><sp>$ ^conflict<n><sg>$ ^several<det><ind><pl>$ ^hundred<n><sg>$ ^thousand<n><sg>$ ^non<adv>$^-<guio>$^Albanian<n><pl>$^,<cm>$ ^particularly<adv>$[ <a href='Serbs'>]^*Serbs$[<\/a>]^,<cm>$[ <a href='Janjevci|Janjevs'>]^*Janjevci$|^*Janjevs$[<\/a>]^,<cm>$ ^and<cnjcoo>$[ <a href='Roma people|Roma'>]^*Roma$ ^person<n><pl>$|^*Roma$[<\/a>]^,<cm>$ ^be<vbser><past>$ ^*forcibly$ ^expel<vblex><pp>$ ^by<pr>$ ^the<det><def><sp>$ ^Albanian<adj>$ ^majority<n><sg>$ ^or<cnjcoo>$ ^flee<vblex><pp>$ ^the<det><def><sp>$ ^province<n><sg>$ ^to<pr>$ ^escape<vblex><inf>$ ^continue<vblex><pp>$ ^ethnic<adj>$ ^violence<n><sg>$^.<sent>$ ^The<det><def><sp>$ ^non<adv>$^-<guio>$^Albanian<adj>$ ^population<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$ ^have<vbhaver><pri><p3><sg>$ ^continue<vblex><pp>$ ^to<pr>$ ^fall<vblex><inf>$ ^in<pr>$ ^since<pr>$ ^the<det><def><sp>$ ^arrival<n><sg>$ ^of<pr>$ ^NATO<n><acr><sg>$ ^and<cnjcoo>$ ^the<det><def><sp>$ ^UN<n><acr><sg>$ ^as a result of<pr>$ ^target<vblex><pp>$ ^violence<n><sg>$^,<cm>$ ^intimidation<n><sg>$ ^and<cnjcoo>$ ^economic<adj>$ ^hardship<n><sg>$^.<sent>$ ^Many<prn><tn><mf><pl>$ ^still<adv>$ ^live<vblex><inf>$ ^in<pr>$ ^communal<adj>$ ^camp<n><pl>$ ^in<pr>$[ <a href='Serbia proper'>]^*Serbia$ ^proper<adj>$[<\/a>]^,<cm>$ ^care<vblex><pp>$ ^for<pr>$ ^by<pr>$ ^international<adj>$ ^relief<n><sg>$ ^agency<n><pl>$ ^and<cnjcoo>$ ^the<det><def><sp>$ ^*Serbian$ ^*governement$^.<sent>$^.<sent>$[][<\/p>
<p>]^According to<pr>$ ^the<det><def><sp>$ ^2000<num>$ ^Living<adj>$ ^Standard<adj>$ ^Measurement<n><sg>$ ^Survey<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^Statistical<adj>$ ^Office<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$[<a href='http:\/\/www.sok-kosovo.org\/pdf\/population\/Kosovo_population.pdf'>]^3<num>$[<\/a>]^,<cm>$ ^Kosovo<np><loc><sg>$^'s<gen>$ ^total<adj>$ ^population<n><sg>$ ^be<vbser><pri><p3><sg>$ ^estimate<vblex><pp>$ ^between<pr>$ ^1,8<num>$ ^and<cnjcoo>$ ^2,0<num>$ ^million<num><sp>$ ^in<pr>$ ^the<det><def><sp>$ ^follow<vblex><ger>$ ^ethnic<adj>$ ^proportion<n><pl>$^:<sent>$^.<sent>$[][<\/p>
<ul>
<li>]^88%<num><percent>$[ <a href='Albanians'>]^Albanian<n><pl>$[<\/a> ]^(<lpar>$^between<pr>$ ^1,584<num>$^,<cm>$^000<num>$ ^and<cnjcoo>$ ^1,733<num>$^,<cm>$^600<num>$^)<rpar>$^.<sent>$[][<\/li>
<li> 
]^7%<num><percent>$[ <a href='Serbs'>]^*Serbs$[<\/a> ]^(<lpar>$^between<pr>$ ^126,000<num>$ ^and<cnjcoo>$ ^140,000<num>$^)<rpar>$^.<sent>$[][<\/li>
<li>	
]^3%<num><percent>$[ <a href='Muslims by nationality|Muslims'>]^Muslim<n><pl>$ ^by<pr>$ ^nationality<n><sg>$|^Muslim<n><pl>$[<\/a> ]^and<cnjcoo>$[ <a href='Bosniaks'>]^*Bosniaks$[<\/a> ]^(<lpar>$^54<num>$ ^to<pr>$ ^60<num>$ ^thousand<n><sg>$^)<rpar>$^.<sent>$[][<\/li>
<li> 
]^2%<num><percent>$[ <a href='Roma people|Roma'>]^*Roma$ ^person<n><pl>$|^*Roma$[<\/a> ]^(<lpar>$^36<num>$ ^to<pr>$ ^40<num>$ ^thousand<n><sg>$^)<rpar>$[ <a href='Roma in Mitrovica Camps'>]^*Roma$ ^in<pr>$ ^*Mitrovica$ ^Camp<n><pl>$^.<sent>$[][<\/a><\/li>
<li>]^1%<num><percent>$[ <a href='Turks'>]^*Turks$[<\/a> ]^(<lpar>$^18<num>$ ^to<pr>$ ^20<num>$ ^thousand<n><sg>$^)<rpar>$^.<sent>$[][<\/li>
<\/ul>
<p>]^*Intercommunal$ ^violence<n><sg>$ ^have<vbhaver><pri><p3><sg>$ ^further<adv>$ ^reduce<vblex><pp>$ ^the<det><def><sp>$ ^number<n><sg>$ ^of<pr>$ ^non<adv>$^-<guio>$^Albanian<n><pl>$ ^in<pr>$ ^Kosovo<np><loc><sg>$ ^since<pr>$ ^this<det><dem><sg>$ ^survey<n><sg>$^,<cm>$ ^and<cnjcoo>$ ^many<prn><tn><mf><pl>$ ^of<pr>$ ^those who<rel><nn><mf><pl>$ ^do<vbdo><pres>$ ^remain<vblex><inf>$ ^now<adv>$ ^live<vblex><inf>$ ^in<pr>$ ^heavily<adv>$ ^*guarded$ ^*enclaves$^.<sent>$^.<sent>$[][<\/p>
<a name="Presidents"><\/a><h2>]^President<n><pl>$^.<sent>$[][<\/h2><ul>
<li><a href='Ibrahim Rugova'>]^Ibrahim<np><ant><m><sg>$ ^*Rugova$[<\/a> ]^(<lpar>$^*deceased$^)<rpar>$^.<sent>$[][<\/li>
<\/ul>
<p><br\/>
<\/p>
<a name="Prime_Ministers"><\/a><h2>]^Prime<adj>$ ^Minister<n><pl>$^.<sent>$[][<\/h2><ul>
<li><a href='Bajram Rexhepi'>]^*Bajram$ ^*Rexhepi$^.<sent>$[][<\/a><\/li>
<li><a href='Ramush Haradinaj'>]^*Ramush$ ^*Haradinaj$[<\/a>]^-<guio>$[<a href='2004'>]^2004<num>$[<\/a>]^-<guio>$[<a href='2005'>]^2005<num>$^.<sent>$[][<\/a><\/li>
<li><a href='Bajram Kosumi'>]^*Bajram$ ^*Kosumi$[<\/a>]^-<guio>$[<a href='2005'>]^2005<num>$[<\/a>]^-<guio>$^present<n><sg>$^.<sent>$[][<\/li>
<\/ul>
<p><br\/>
<\/p>
<a name="See_also"><\/a><h2>]^See<vblex><pres>$ ^also<adv>$^.<sent>$[][<\/h2><ul>
<li><a href='Assembly of Kosovo'>]^Assembly<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$^.<sent>$[][<\/a><\/li>
<li><a href='Government of Kosovo'>]^Government<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$^.<sent>$[][<\/a><\/li>
<li><a href='Prime Minister of Kosovo'>]^Prime<adj>$ ^Minister<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$^.<sent>$[][<\/a><\/li>
<li><a href='President of Kosovo'>]^President<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$^.<sent>$[][<\/a><\/li>
<li><a href='Post and Telecom of Kosovo'>]^Post<n><sg>$ ^and<cnjcoo>$ ^*Telecom$ ^of<pr>$ ^Kosovo<np><loc><sg>$^.<sent>$[][<\/a><\/li>
<li><a href='Battle of Kosovo|Battle of Kosovo (1389)'>]^Battle<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$|^Battle<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$ ^(<lpar>$^1389<num>$^)<rpar>$^.<sent>$[][<\/a><\/li>
<li><a href='Demographic history of Kosovo'>]^*Demographic$ ^history<n><sg>$ ^of<pr>$ ^Kosovo<np><loc><sg>$^.<sent>$[][<\/a><\/li>
<li><a href='Municipalities of Kosovo'>]^Municipality<n><pl>$ ^of<pr>$ ^Kosovo<np><loc><sg>$^.<sent>$[][<\/a><\/li>
<li><a href='National awakening and the birth of Albania'>]^National<adj>$ ^awaken<vblex><ger>$ ^and<cnjcoo>$ ^the<det><def><sp>$ ^birth<n><sg>$ ^of<pr>$ ^*Albania$^.<sent>$[][<\/a><\/li>
<li><a href='Subdivisions of Kosovo'>]^*Subdivisions$ ^of<pr>$ ^Kosovo<np><loc><sg>$^.<sent>$[][<\/a><\/li>
<li><a href='Unrest in Kosovo'>]^Unrest<n><sg>$ ^in<pr>$ ^Kosovo<np><loc><sg>$[<\/a> ]^(<lpar>$^about<pr>$ ^the<det><def><sp>$ ^March<n><sg>$ ^2004<num>$ ^unrest<n><sg>$^)<rpar>$^.<sent>$[][<\/li>
<\/ul>
<p>&lt;]^!<sent>$^-<guio>$^-<guio>$^Prpers<prn><subj><p3><nt><sg>$ ^appear<vblex><pri><p3><sg>$ ^that<cnjsub>$ ^this<prn><tn><mf><sg>$ ^be<vbser><pri><p3><sg>$ ^a<det><ind><sg>$ ^actual<adj>$ ^article<n><sg>$^,<cm>$ ^but<cnjcoo>$ ^prpers<prn><subj><p3><nt><sg>$ ^be<vbser><past><p3><sg>$ ^remove<vblex><pp>$ *[ <a href='Sexual trafficking in Kosovo'>]^Sexual<adj>$ ^trafficking<n><sg>$ ^in<pr>$ ^Kosovo<np><loc><sg>$[<\/a> ]^-<guio>$^-<guio>$^.<sent>$[][&gt;<\/p>
<a name="External_links"><\/a><h2>]^External<adj>$ ^link<n><pl>$^.<sent>$[][<\/h2><p>]{{^*sisterlinks$|^Kosovo<np><loc><sg>$}}^.<sent>$[][<\/p>
<ul>
<li><a href='https:\/\/www.osce.org\/documents\/mik\/1999\/11\/1620_en.pdf Human Rights in Kosovo: As Seen, As Told. Volume I, October 1998 - June 1999'>]^4<num>$[<\/a>]^.<sent>$^.<sent>$[][<\/li>
<li><\/li>
<li><a href='http:\/\/www.lib.utexas.edu\/maps\/kosovo.html Kosovo maps from the Perry-CastaÃ±eda Library Map Collection'>]^5<num>$^.<sent>$[][<\/a><\/li>
<li><a href='http:\/\/www.chmouel.com\/geeklog\/gallery\/gallery_individual.php\/mkosovo\/ A collection of photos from Kosovo'>]^6<num>$^.<sent>$[][<\/a><\/li>
<li><a href='http:\/\/www.balkanpeace.org\/hed\/archive\/nov01\/hed4304.shtml Al Qaeda involvement in Kosovo'>]^7<num>$^.<sent>$[][<\/a><\/li>
<\/ul>
<p> 
<br\/>
<\/p>
<a name="Pro-Albanian"><\/a><h3>]^*Pro$^-<guio>$^Albanian<n><sg>$^.<sent>$[][<\/h3><ul>
<li><a href='http:\/\/BalkanUpdate.blogspot.com Balkan Update'>]^8<num>$[<\/a>]^-<guio>$ ^A<det><ind><sg>$ ^*blog$ ^with<pr>$ ^news<n><sg>$^,<cm>$ ^analysis<n><sg>$ ^and<cnjcoo>$ ^the<det><def><sp>$ ^*lates$ ^update<vblex><pri><p3><sg>$ ^from<pr>$ ^*Balkans$^.<sent>$[][<\/li>
<li><a href='http:\/\/www.eciks.org Economic Initiative for Kosovo'>]^9<num>$[<\/a> ]^-<guio>$ "^.<sent>$^.<sent>$^.<sent>$^late<adj><sint><sup>$ ^news<n><sg>$^,<cm>$ ^analysis<n><sg>$ ^and<cnjcoo>$ ^publication<n><pl>$ ^from<pr>$ ^the<det><def><sp>$ ^*Kosovar$ ^economy<n><sg>$"^.<sent>$[][<\/li>
<li><a href='http:\/\/www.rtklive.com  RTK'>]^10<num>$[<\/a> ]^-<guio>$ ^*Kosova$^'s<gen>$ ^public<adj>$ ^television<n><sg>$ ^(<lpar>$^news<n><sg>$ ^in<pr>$ ^Albanian<n><sg>$^,<cm>$ ^*Serbian$^,<cm>$ ^Turkish<adj>$ ^and<cnjcoo>$ ^*Roma$^)<rpar>$^.<sent>$[][<\/li>
<li><a href='http:\/\/www.albanian.com\/main\/countries\/kosova Albanian.com'>]^11<num>$[<\/a> ]^-<guio>$ ^general<adj>$ ^information<n><sg>$^.<sent>$[][<\/li>
<li><a href='http:\/\/www.kosovaelire.com\/ Kosova e lirÃ«'>]^12<num>$[<\/a> ]^(<lpar>$^Free<adj><sint>$ ^*Kosova$^)<rpar>$ ^-<guio>$^-<guio>$ ^Material<n><sg>$ ^about<pr>$ ^*Kosovars$ ^and<cnjcoo>$ ^Albanian<n><pl>$ ^in<pr>$ ^Albanian<adj>$ ^language<n><sg>$^.<sent>$^.<sent>$[][<\/li>
<li> 
<a href='http:\/\/beqiraj.com\/kosova\/de\/ General information from Beqiraj.com'>]^13<num>$[<\/a> ]^(<lpar>$^in<pr>$ ^German<adj>$^)<rpar>$^.<sent>$[][<\/li>
<li><a href='http:\/\/beqiraj.com\/kosova\/al\/ General information from Beqiraj.com'>]^14<num>$[<\/a> ]^(<lpar>$^in<pr>$ ^Albanian<n><sg>$^)<rpar>$^.<sent>$[][<\/li>
<li><a href='http:\/\/www.alb-shkenca.org\/images\/stories\/Why%20Independence.pdf Why Independence for Kosovo?'>]^15<num>$[<\/a> ]^A<det><ind><sg>$ ^summary<n><sg>$ ^of<pr>$ ^the<det><def><sp>$ ^case<n><sg>$ ^for<pr>$ ^a<det><ind><sg>$ ^independent<adj>$ ^*Kosova$ ^by<pr>$ ^two<num><sp>$ ^*Prishtina$ ^intellectual<n><pl>$^.<sent>$[][<\/li>
<\/ul>
<p><br\/>
<\/p>
<a name="Pro-Serb"><\/a><h3>]^*Pro$^-<guio>$^*Serb$^.<sent>$[][<\/h3><ul>
<li><a href='http:\/\/www.kosovo.com\/sk\/history\/kosovo_origins\/default.htm  Hugo Roth, <em>]^Kosovo<np><loc><sg>$ ^Origin<n><pl>$[<\/em>]^'<apos>$[>]^16<num>$[<\/a>]^:<sent>$ ^a<det><ind><sg>$ ^historian<n><sg>$^'s<gen>$ ^comprehensive<adj>$ ^*overview$^.<sent>$[][<\/li>
<li><a href='http:\/\/www.kosovo.com\/ Kosovo.com'>]^17<num>$[<\/a> ]^*Serbian$ ^Orthodox<adj>$ ^Church<n><sg>$^'s<gen>$ ^official<adj>$ ^*website$ ^on<pr>$ ^Kosovo<np><loc><sg>$^.<sent>$[][<\/li>
<li><\/li>
<li><a href='http:\/\/www.rastko.org.yu\/kosovo\/crucified\/default.htm Account of destroyed Serbian Orthodox churches in Kosovo and Metohija'>]^18<num>$^.<sent>$[][<\/a><\/li>
<li><a href='http:\/\/groups.yahoo.com\/group\/decani\/ Kosovo Newsgroup archive'>]^19<num>$^.<sent>$[][<\/a><\/li>
<li><a href='http:\/\/www.kc.gov.yu\/ Coordination Center of SCG and the Republic of Serbia for Kosovo'>]^20<num>$^.<sent>$[][<\/a><\/li>
<li><a href='http:\/\/www.srbija.sr.gov.yu\/kosovo-metohija\/ Serbian Government Kosovo-Metohija site'>]^21<num>$^.<sent>$[][<\/a><\/li>
<li><a href='http:\/\/www.tserkovnost.org\/srbija\/ Eastern Orthodox Resource Centre'>]^22<num>$^.<sent>$[][<\/a><\/li>
<\/ul>
<p><br\/>
]{{^*Serbia$ ^and<cnjcoo>$ ^Montenegro<np><loc><sg>$}}^.<sent>$[][<\/p>
<p><a href='Category:Disputed territories'>]^Category<n><sg>$^:<sent>$^*Disputed$ ^territory<n><pl>$[<\/a>
<a href='Category:Kosovo| '>]^Category<n><sg>$^:<sent>$^Kosovo<np><loc><sg>$|[ <\/a>
<a href='Category:United Nations'>]^Category<n><sg>$^:<sent>$^Unite<vblex><pp>$ ^Nation<n><pl>$^.<sent>$[][<\/a><\/p>
<p><a href='ar:ÙÙØµÙØ©'>]^*ar$^:<sent>$^*Ù$^*Ù$Øµ^*Ù$Ø©[<\/a>
<a href='ast:Kosovo'>]^*ast$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='bg:ÐÐ¾ÑÐ¾Ð²Ð¾'>]^*bg$^:<sent>$ÐÐ¾^*Ñ$Ð¾Ð²Ð¾[<\/a>
<a href='bs:Kosovo'>]^*bs$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='ca:Kosovo'>]^*ca$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='cs:Kosovo'>]^*cs$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='da:Kosovo'>]^*da$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='de:Kosovo'>]^*de$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='et:Kosovo'>]^*et$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='es:Kosovo'>]^*es$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='eo:Kosovo'>]^*eo$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='fr:Kosovo'>]^*fr$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='ko:ì½ìë³´'>]^*ko$^:<sent>$^*ì$½^*ì$^*ë$³´[<\/a>
<a href='hr:Kosovo'>]^*hr$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='id:Kosovo'>]^*id$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='it:Kosovo'>]^prpers<prn><obj><p3><nt><sg>$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='he:×§××¡××× ×××××××'>]^prpers<prn><subj><p3><m><sg>$^:<sent>$×§××^¡<lquest>$××× ×××××××[<\/a>
<a href='lt:Kosovas'>]^*lt$^:<sent>$^*Kosovas$[<\/a>
<a href='hu:KoszovÃ³'>]^*hu$^:<sent>$^*Koszov$Ã³[<\/a>
<a href='mk:ÐÐ¾ÑÐ¾Ð²Ð¾'>]^*mk$^:<sent>$ÐÐ¾^*Ñ$Ð¾Ð²Ð¾[<\/a>
<a href='nl:Kosovo'>]^*nl$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='nds:Kosovo'>]^*nds$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='ja:ã³ã½ã'>]^*ja$^:<sent>$ã³ã½ã[<\/a>
<a href='no:Kosovo'>]^no<adv>$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='nn:Kosovo'>]^*nn$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='pl:Kosowo i Metohija'>]^*pl$^:<sent>$^*Kosowo$ ^*i$ ^*Metohija$[<\/a>
<a href='pt:Kosovo'>]^*pt$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='ro:Kosovo'>]^*ro$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='ru:ÐÐ¾ÑÐ¾Ð²Ð¾'>]^*ru$^:<sent>$ÐÐ¾^*Ñ$Ð¾Ð²Ð¾[<\/a>
<a href='sq:Kosova'>]^*sq$^:<sent>$^*Kosova$[<\/a>
<a href='sr:ÐÐ¾ÑÐ¾Ð²Ð¾ Ð¸ ÐÐµÑÐ¾ÑÐ¸ÑÐ°'>]^*sr$^:<sent>$ÐÐ¾^*Ñ$Ð¾Ð²Ð¾ Ð¸ ÐÐµ^*Ñ$Ð¾^*Ñ$Ð¸^*Ñ$Ð°[<\/a>
<a href='fi:Kosovo'>]^*fi$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='sv:Kosovo'>]^*sv$^:<sent>$^Kosovo<np><loc><sg>$[<\/a>
<a href='tr:Kosova'>]^*tr$^:<sent>$^*Kosova$[<\/a>
<a href='uk:ÐÐ¾ÑÐ¾Ð²Ð¾'>]^*uk$^:<sent>$ÐÐ¾^*Ñ$Ð¾Ð²Ð¾^.<sent>$[][<\/a><\/p>
<\/body>
<\/html>
]